const I={home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1v-9Z"/></svg>',chat:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3 1.6-4.8A7 7 0 0 1 3 13V8a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v7Z"/></svg>',users:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/></svg>',memory:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="5" width="14" height="14" rx="3"/><path d="M9 2v3m6-3v3M9 19v3m6-3v3M2 9h3m-3 6h3m14-6h3m-3 6h3M9 9h6v6H9z"/></svg>',settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.1h-4v-.1A1.7 1.7 0 0 0 9 19.4a1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3.1 14H3v-4h.1A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3.1V3h4v.1A1.7 1.7 0 0 0 15 4.6a1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.1v4h-.1a1.7 1.7 0 0 0-1.5 1Z"/></svg>',plus:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>',back:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m15 18-6-6 6-6"/></svg>',more:'<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>',send:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m22 2-7 20-4-9-9-4 20-7Z"/><path d="M22 2 11 13"/></svg>',edit:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4L16.5 3.5Z"/></svg>',trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 6h18M8 6V4h8v2m3 0-1 15H6L5 6m5 4v7m4-7v7"/></svg>'};

const KEY='storyverse-data-v2';
const now=()=>new Date().toISOString();
const uid=p=>p+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const seed={
 stories:[
  {id:'s-magic',name:'魔法学院',summary:'初入阿斯特拉学院，禁林深处的古老封印却意外松动。',worldview:'这是一个人类与魔法共同存在的世界。',background:'你刚进入王国最大的魔法学院学习。',plot:'森林边缘出现陌生的魔力波动，调查队准备明早出发。',important:'魔法有明确的属性与代价；学院禁止学生私自进入禁林。',player:{name:'我',gender:'未知',age:'未知',identity:'魔法学院新生',appearance:'未知'},theme:'magic',updatedAt:now()},
  {id:'s-end',name:'末日世界',summary:'城市陷入沉寂之后，在废墟中寻找最后的信号。',worldview:'灾难后的近未来世界。',background:'你在避难所醒来。',plot:'无线电接收到未知求救信号。',important:'资源稀缺，角色不知道自己未亲历的事情。',player:{name:'我',gender:'未知',age:'未知',identity:'幸存者',appearance:'未知'},theme:'ember',updatedAt:'2026-08-25T10:00:00Z'}
 ],
 characters:[
  {id:'c-alice',storyId:'s-magic',name:'爱丽丝',gender:'女',age:'17',role:'火系魔法师 · 同班同学',intro:'出身古老魔法世家，总把关心藏在不耐烦的语气后面。',personality:'傲娇、活泼、嘴硬心软',speech:'语气轻快，偶尔吐槽，不直接承认关心别人',background:'来自北境的魔法世家，自小接受严格训练。',relation:'信任用户，但还不愿坦率表达。',tone:0},
  {id:'c-snow',storyId:'s-magic',name:'小雪',gender:'女',age:'16',role:'治愈系魔法师 · 室友',intro:'总能第一时间发现新鲜事，是学院里可靠的消息来源。',personality:'热情、话多、好奇心强',speech:'情绪鲜明，喜欢使用感叹句',background:'来自普通商人家庭，第一次离开家乡。',relation:'把用户当作最亲近的朋友。',tone:1},
  {id:'c-arthur',storyId:'s-magic',name:'亚瑟',gender:'男',age:'19',role:'剑术课助教 · 学长',intro:'做事一丝不苟，常默默替调查队准备好需要的东西。',personality:'冷静、认真、寡言',speech:'言简意赅，很少使用感叹句',background:'曾是王国骑士预备役。',relation:'认可用户的潜力，但会严格要求。',tone:2}
 ],
 chats:[
  {id:'p-alice',storyId:'s-magic',type:'private',name:'爱丽丝',memberIds:['c-alice'],updatedAt:now()},
  {id:'p-snow',storyId:'s-magic',type:'private',name:'小雪',memberIds:['c-snow'],updatedAt:'2026-08-27T21:06:00Z'},
  {id:'g-forest',storyId:'s-magic',type:'group',name:'森林调查队',memberIds:['c-alice','c-snow','c-arthur'],updatedAt:'2026-08-28T10:24:00Z'}
 ],
 messages:[
  {id:'m1',chatId:'p-alice',senderId:'c-alice',text:'你总算来了。再晚一点，图书馆就要关门了。',time:'19:42'},
  {id:'m2',chatId:'p-alice',senderId:'user',text:'路上遇到一只会说话的猫，它说禁林最近很不安静。',time:'19:43'},
  {id:'m3',chatId:'p-alice',senderId:'c-alice',text:'会说话的猫？学院里会说话的东西可多了。不过……禁林的魔力波动确实不太对。',time:'19:43'},
  {id:'m4',chatId:'g-forest',senderId:'user',text:'今天谁陪我去森林？',time:'10:21'},
  {id:'m5',chatId:'g-forest',senderId:'c-alice',text:'我可以去，不过得早点回来。',time:'10:22'},
  {id:'m6',chatId:'g-forest',senderId:'c-snow',text:'等等，我也要去！听说昨晚有人在森林边缘看见了蓝色的光。',time:'10:22'},
  {id:'m7',chatId:'g-forest',senderId:'c-arthur',text:'先准备一些恢复药。森林里的魔力波动还不稳定。',time:'10:24'}
 ],
 memories:[{id:'mem1',storyId:'s-magic',text:'调查队在森林深处发现了一座被藤蔓覆盖的地下遗迹。',knownBy:['c-alice','c-snow','c-arthur'],when:'今天上午'}],
 apis:[],agents:[],currentStoryId:'s-magic'
};
function migrate(d){
 d.stories.forEach(s=>{s.player??={name:'我',gender:'未知',age:'未知',identity:'未知',appearance:'未知'};s.player.gender??='未知'});
 d.chats.forEach(c=>c.scene??={environment:'',autoMemory:true});
 d.memories??=[];d.memories.forEach(m=>{m.knownBy=Array.isArray(m.knownBy)?m.knownBy:[];m.when??='时间未知';m.createdAt??=now()});
 if(!Array.isArray(d.apis)){d.apis=[];if(d.api?.baseUrl)d.apis.push({id:'api-migrated',name:d.api.name||'原有接口',baseUrl:d.api.baseUrl,apiKey:d.api.apiKey||'',separator:!!d.api.separator,models:d.api.model?[d.api.model]:[]})}
 if(!Array.isArray(d.agents)){d.agents=[];if(d.apis[0]&&d.api?.model)d.agents.push({id:'agent-migrated',name:'默认智能体',apiId:d.apis[0].id,model:d.api.model})}
 d.characters.forEach(c=>{if(c.agentId===undefined)c.agentId=d.agents[0]?.id||''});
 return d;
}
// 正常业务数据仍保留原来的 key；统一存储入口便于后续迁移，但不改变现有数据格式。
function load(){const d=window.StoryVerseStorage.readJSON(KEY,null);return migrate(d&&d.stories?d:structuredClone(seed))}
let db=load();
const params=new URLSearchParams(location.search);
const initialPage=['home','story','characters','chats','chat','scenes','settings','memory'].includes(params.get('page'))?params.get('page'):'home';
const state={page:initialPage,tab:params.get('tab')||'overview',chatId:params.get('chat')||'p-alice',modal:params.get('modal')||null,editingId:null,sourceMessageId:null,actionMessageId:params.get('message')||null,actionAnchor:null,confirmDelete:false,typingId:null,sending:false,summarizing:false,agentApiId:'',agentNameDraft:''};
function save(){window.StoryVerseStorage.writeJSON(KEY,db)}
function e(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function story(){return db.stories.find(x=>x.id===db.currentStoryId)||db.stories[0]}
function chars(sid=db.currentStoryId){return db.characters.filter(x=>x.storyId===sid)}
function chats(sid=db.currentStoryId){return db.chats.filter(x=>x.storyId===sid).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))}
function char(id){return db.characters.find(x=>x.id===id)}
function api(id){return db.apis.find(x=>x.id===id)}
function agent(id){return db.agents.find(x=>x.id===id)}
function chat(id=state.chatId){return db.chats.find(x=>x.id===id)}
function msgList(id=state.chatId){return db.messages.filter(x=>x.chatId===id)}
function av(c,small=false){if(!c)return`<div class="avatar tone-3 ${small?'small':''}">✦</div>`;return`<div class="avatar tone-${c.tone??3} ${small?'small':''}">${e(c.name.slice(0,1))}</div>`}
function toast(t){const x=document.querySelector('.toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
function fmtTime(v){if(!v)return'';const d=new Date(v),n=new Date(),diff=n-d;if(diff<864e5)return'今天';if(diff<1728e5)return'昨天';return`${d.getMonth()+1}/${d.getDate()}`}
function latest(c){const m=msgList(c.id).at(-1);return m?m.text:(c.type==='group'?`${c.memberIds.length} 位人物`:'开始一段新对话')}

function appbar(title,sub='',backTo=''){return`<header class="appbar"><div class="appbar-left">${backTo?`<button class="back" data-go="${backTo}">${I.back}</button>`:''}<div><div class="appbar-title">${e(title)}</div>${sub?`<div class="appbar-sub">${e(sub)}</div>`:''}</div></div><button class="icon-btn" data-go="settings">${I.settings}</button></header>`}
function nav(active){return`<nav class="bottom-nav"><button data-go="home" class="${active==='home'?'active':''}">${I.home}<span>故事</span></button><button data-go="story" class="${active==='story'?'active':''}">${I.chat}<span>聊天</span></button><button data-go="characters" class="${active==='characters'?'active':''}">${I.users}<span>人物</span></button><button data-go="settings" class="${active==='settings'?'active':''}">${I.settings}<span>设置</span></button></nav>`}
function shell(body,bar='',active='home',fab=''){return`<div class="desktop-stage"><div class="phone">${bar}${body}${fab}${nav(active)}<div class="toast"></div>${modal()}</div></div>`}

function homePage(){return shell(`<main class="screen"><div class="eyebrow">STORYVERSE</div><h1 class="page-title">我的故事</h1><p class="page-copy">选择一个世界，继续你们未完的故事。</p><div class="story-list">${db.stories.map(s=>{const cs=chars(s.id);return`<article class="story-card" data-story="${s.id}" data-theme="${e(s.theme||'magic')}"><span class="story-badge">${cs.length} 位人物 · ${chats(s.id).length} 个聊天</span><h2>${e(s.name)}</h2><p>${e(s.summary)}</p><div class="story-meta"><div class="avatar-stack">${cs.slice(0,3).map(x=>av(x,true)).join('')}</div><span>${fmtTime(s.updatedAt)}聊过</span></div></article>`}).join('')||'<div class="empty-card">还没有故事，点击右下角开始创造。</div>'}</div></main>`,appbar('StoryVerse','故事，由你继续'),'home',`<button class="fab" data-modal="story">${I.plus}</button>`)}
function storyTabs(){return`<div class="tab-row">${[['overview','概览'],['chats','聊天'],['characters','人物'],['memory','记忆'],['settings','设置']].map(x=>`<button data-tab="${x[0]}" class="${state.tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</div>`}
function chatRows(){return chats().map(c=>{const first=char(c.memberIds[0]);return`<button class="list-row" data-chat="${c.id}">${c.type==='group'?av(null):av(first)}<div><div class="row-title">${e(c.name)}</div><div class="row-preview">${e(latest(c))}</div></div><span class="row-time">${fmtTime(c.updatedAt)}</span></button>`}).join('')||'<div class="empty-card">还没有聊天。创建人物后会自动生成私聊。</div>'}
function overview(){const s=story();return`<div class="section-head"><h2>最近聊天</h2><span>${chats().length} 个</span></div><div class="list">${chatRows()}</div><div class="section-head"><h2>故事状态</h2></div><section class="panel stats"><div class="stat"><span>当前剧情</span><strong>${e(s.plot||'尚未设置')}</strong></div><div class="stat"><span>登场人物</span><strong>${chars().length} 位</strong></div><div class="stat"><span>聊天消息</span><strong>${db.messages.filter(m=>chats().some(c=>c.id===m.chatId)).length} 条</strong></div></section>`}
function charactersContent(){const p=story().player;return`<div class="section-head"><h2>我的角色</h2><span>其他人物眼中的你</span></div><article class="character-card player-card"><div class="character-top"><div class="avatar tone-4">我</div><div class="character-info"><div class="character-name">${e(p.name||'我')}</div><div class="character-role">${e(p.identity||'未知身份')}</div></div><button class="icon-btn" data-modal="player">${I.edit}</button></div><p class="character-desc">性别：${e(p.gender||'未知')} · 年龄：${e(p.age||'未知')}<br>外貌：${e(p.appearance||'未知')}</p></article><div class="section-head"><h2>AI 人物</h2><button class="btn small primary" data-modal="character">${I.plus}创建</button></div><div class="character-list">${chars().map(c=>{const a=agent(c.agentId);return`<article class="character-card"><div class="character-top">${av(c)}<div class="character-info"><div class="character-name">${e(c.name)}</div><div class="character-role">${e(c.role)}</div></div><button class="icon-btn" data-edit-char="${c.id}">${I.edit}</button></div><p class="character-desc">${e(c.intro||'还没有人物介绍。')}</p><div class="chips">${String(c.personality||'').split(/[、,，]/).filter(Boolean).slice(0,3).map(t=>`<span class="chip">${e(t)}</span>`).join('')}<span class="chip agent-chip">${a?'智能体：'+e(a.name):'未绑定智能体'}</span></div><div class="card-actions"><button class="btn small primary" data-private="${c.id}">${I.chat}开始私聊</button></div></article>`}).join('')||'<div class="empty-card">故事里还没有 AI 人物。</div>'}</div>`}
function storySettings(){const s=story();return`<div class="section-head"><h2>故事设定</h2><button class="btn small" data-edit-story="${s.id}">${I.edit}编辑</button></div><section class="panel stats"><div class="stat"><span>故事简介</span><strong>${e(s.summary)}</strong></div><div class="stat"><span>世界观</span><strong>${e(s.worldview||'尚未填写')}</strong></div><div class="stat"><span>故事背景</span><strong>${e(s.background||'尚未填写')}</strong></div><div class="stat"><span>当前剧情</span><strong>${e(s.plot||'尚未填写')}</strong></div></section><div class="danger-zone"><button class="btn danger full" data-delete-story="${s.id}">${I.trash}删除这个故事</button></div>`}
function storyPage(){const s=story();let content;if(state.tab==='overview')content=overview();else if(state.tab==='chats')content=`<div class="section-head"><h2>全部聊天</h2><button class="btn small primary" data-modal="group">${I.plus}新建群聊</button></div><div class="list">${chatRows()}</div>`;else if(state.tab==='characters')content=charactersContent();else if(state.tab==='memory')content=memoryContent();else content=storySettings();return shell(`<main class="screen"><section class="hero"><div class="hero-kicker">当前剧情</div><h1>${e(s.name)}</h1><p>${e(s.plot||s.summary)}</p></section>${storyTabs()}${content}</main>`,appbar(s.name,'我的故事 / 当前故事','home'),'story',state.tab==='chats'?`<button class="fab" data-modal="group">${I.plus}</button>`:'')}
function charactersPage(){return shell(`<main class="screen"><div class="eyebrow">CHARACTERS</div><h1 class="page-title">故事人物</h1><p class="page-copy">人物属于《${e(story().name)}》，可以出现在多个私聊和群聊中。</p>${charactersContent()}</main>`,appbar('故事人物',story().name,'story'),'characters')}

function chatPage(){const c=chat();if(!c){state.page='story';return storyPage()}const members=c.memberIds.map(char).filter(Boolean);return`<div class="desktop-stage"><div class="phone"><section class="chat-shell"><header class="chat-header"><div class="chat-person"><button class="back" data-go="story">${I.back}</button>${c.type==='group'?av(null):av(members[0])}<div><div class="appbar-title">${e(c.name)}</div><div class="online">${c.type==='group'?`${members.length} 位人物 · 自然接话模式`:'在线 · '+e(members[0]?.role||'')}</div></div></div><button class="icon-btn" data-chat-menu aria-label="场景设置">${I.more}</button></header><div class="messages" id="messages"><div class="day">今天</div>${msgList().map(messageHtml).join('')}${state.typingId?`<div class="typing"><span class="dots"><i></i><i></i><i></i></span>${e(char(state.typingId)?.name||'角色')}正在输入…</div>`:''}${state.summarizing?`<div class="typing summary-typing"><span class="dots"><i></i><i></i><i></i></span>正在整理当前记忆…</div>`:''}</div><div class="composer-area"><div class="composer"><textarea id="composer" rows="1" placeholder="写下你想说的话…" ${state.sending?'disabled':''}></textarea><button class="send" id="send" ${state.sending?'disabled':''}>${I.send}</button></div></div></section><div class="toast"></div>${modal()}</div></div>`}
function messageHtml(m){const c=m.senderId==='user'?null:char(m.senderId),display=m.senderId==='user'||m.error?m.text:normalize(m.text,c,chat(m.chatId));return`<div class="message ${m.senderId==='user'?'mine':''} ${state.modal==='bubbleActions'&&state.actionMessageId===m.id?'message-selected':''}" data-message-id="${m.id}">${m.senderId==='user'?'':av(c,true)}<div class="message-content"><div class="sender">${m.senderId==='user'?'我':e(c?.name||'未知人物')}</div><div class="bubble ${m.error?'error-bubble':''}" title="长按或右键操作">${e(display)}</div><div class="msg-time">${e(m.time||'')}</div>${m.error?`<button class="retry" data-retry="${m.id}">重新发送</button>`:''}</div></div>`}

function settingsPage(){return shell(`<main class="screen"><div class="eyebrow">AI MANAGEMENT</div><h1 class="page-title">AI 管理</h1><p class="page-copy">先接入一个或多个接口，再用接口中的模型创建智能体。人物可以分别绑定不同智能体。</p><div class="section-head"><h2>接口</h2><button class="btn small primary" data-modal="api">${I.plus}添加</button></div><div class="manage-list">${db.apis.map(a=>`<article class="manage-card"><div class="manage-icon">API</div><div class="manage-info"><strong>${e(a.name)}</strong><span>${e(a.baseUrl)}</span><small>${a.models?.length||0} 个已识别模型</small></div><button class="icon-btn" data-edit-api="${a.id}">${I.edit}</button></article>`).join('')||'<div class="empty-card">还没有接口。添加后即可读取模型列表。</div>'}</div><div class="section-head"><h2>智能体</h2><button class="btn small primary" data-modal="agent">${I.plus}创建</button></div><div class="manage-list">${db.agents.map(a=>{const source=api(a.apiId);return`<article class="manage-card"><div class="manage-icon agent-icon">AI</div><div class="manage-info"><strong>${e(a.name)}</strong><span>${e(source?.name||'接口已删除')}</span><small>${e(a.model)}</small></div><button class="icon-btn" data-edit-agent="${a.id}">${I.edit}</button></article>`}).join('')||'<div class="empty-card">还没有智能体。智能体决定人物使用哪个接口和模型。</div>'}</div><p class="note" style="margin-top:18px">密钥只保存在当前浏览器的本机存储中，并由本地服务转发给你选择的接口。</p></main>`,appbar('AI 管理','接口与智能体','story'),'settings')}
function memoryContent(){const ms=db.memories.filter(x=>x.storyId===db.currentStoryId);return`<div class="section-head"><h2>故事共同记忆</h2><button class="btn small primary" data-modal="memory">${I.plus}添加</button></div><p class="note memory-note">只有被标记为“知道”的人物才会在对话中获得对应记忆。</p><div class="memory-list">${ms.map((m,i)=>{const known=m.knownBy.map(id=>char(id)?.name).filter(Boolean),unknown=chars().filter(c=>!m.knownBy.includes(c.id)).map(c=>c.name);return`<article class="memory-card"><div class="memory-num">${i+1}</div><div><div class="memory-text">${e(m.text)}</div><div class="memory-meta">${e(m.when)}${m.sourceChatId?` · 来自“${e(chat(m.sourceChatId)?.name||'已删除的聊天')}”`:''}</div><div class="memory-access"><span>知道：${e(known.join('、')||'无人')}</span>${unknown.length?`<small>不知道：${e(unknown.join('、'))}</small>`:''}</div></div><button class="icon-btn memory-edit" data-edit-memory="${m.id}">${I.edit}</button></article>`}).join('')||'<div class="empty-card">还没有共同记忆。可以手动添加，或从聊天记录中选取重要消息。</div>'}</div>`}
function memoriesPage(){return shell(`<main class="screen"><div class="eyebrow">STORY MEMORY</div><h1 class="page-title">故事记忆</h1><p class="page-copy">管理这个故事发生过的重要事件，以及哪些人物知道它们。</p>${memoryContent()}</main>`,appbar('故事记忆',story().name,'story'),'story')}

function modal(){if(!state.modal)return'';if(state.modal==='story'||state.modal==='editStory')return storyModal();if(state.modal==='character'||state.modal==='editCharacter')return characterModal();if(state.modal==='group')return groupModal();if(state.modal==='player')return playerModal();if(state.modal==='api'||state.modal==='editApi')return apiModal();if(state.modal==='agent'||state.modal==='editAgent')return agentModal();if(state.modal==='memory'||state.modal==='editMemory')return memoryModal();if(state.modal==='sceneSettings')return sceneSettingsModal();if(state.modal==='bubbleActions')return bubbleActionsModal();if(state.modal==='editMessage')return messageEditModal();return''}
function storyModal(){const s=state.modal==='editStory'?db.stories.find(x=>x.id===state.editingId):{};return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${s?.id?'编辑故事':'创建新故事'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="story-form"><div class="field"><label>故事名称</label><input name="name" value="${e(s?.name)}" required placeholder="给这个世界起个名字" /></div><div class="field"><label>故事简介</label><textarea name="summary" required placeholder="用一两句话介绍故事">${e(s?.summary)}</textarea></div><div class="field"><label>世界观</label><textarea name="worldview" placeholder="这个世界遵循怎样的规则？">${e(s?.worldview)}</textarea></div><div class="field"><label>故事背景</label><textarea name="background" placeholder="故事从哪里开始？">${e(s?.background)}</textarea></div><div class="field"><label>当前剧情</label><textarea name="plot" placeholder="现在正在发生什么？">${e(s?.plot)}</textarea></div><div class="field"><label>重要设定</label><textarea name="important" placeholder="AI 必须知道的规则">${e(s?.important)}</textarea></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">${s?.id?'保存修改':'创建故事'}</button></div></form></section></div>`}
function characterModal(){const c=state.modal==='editCharacter'?char(state.editingId):{};return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${c?.id?'编辑人物':'创建人物'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="character-form"><div class="field"><label>人物名字</label><input name="name" value="${e(c?.name)}" required /></div><div class="inline-fields"><div class="field"><label>性别</label><input name="gender" value="${e(c?.gender)}" placeholder="未知" /></div><div class="field"><label>年龄</label><input name="age" value="${e(c?.age)}" placeholder="未知" /></div></div><div class="field"><label>使用的智能体</label><select name="agentId"><option value="">未指定（使用示例回复）</option>${db.agents.map(a=>`<option value="${a.id}" ${c?.agentId===a.id?'selected':''}>${e(a.name)} · ${e(a.model)}</option>`).join('')}</select><small>智能体决定这个人物通过哪个接口和模型回复。</small></div><div class="field"><label>身份</label><input name="role" value="${e(c?.role)}" placeholder="例如：魔法学院学生" /></div><div class="field"><label>人物介绍</label><textarea name="intro">${e(c?.intro)}</textarea></div><div class="field"><label>性格</label><input name="personality" value="${e(c?.personality)}" placeholder="例如：开朗、勇敢、容易冲动" /></div><div class="field"><label>说话方式</label><textarea name="speech">${e(c?.speech)}</textarea></div><div class="field"><label>背景故事</label><textarea name="background">${e(c?.background)}</textarea></div><div class="field"><label>和我的关系</label><textarea name="relation">${e(c?.relation)}</textarea></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">${c?.id?'保存修改':'创建人物'}</button></div>${c?.id?`<button type="button" class="btn danger full" data-delete-char="${c.id}">${I.trash}删除人物</button>`:''}</form></section></div>`}
function playerModal(){const p=story().player;return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>我的角色</h2><button class="icon-btn" data-close>×</button></div><p class="page-copy">这些资料会告诉故事中的 AI 人物“你是谁”。不确定的项目可以保留“未知”。</p><form class="form" id="player-form"><div class="field"><label>姓名</label><input name="name" value="${e(p.name||'我')}" placeholder="未知" /></div><div class="inline-fields"><div class="field"><label>性别</label><input name="gender" value="${e(p.gender||'未知')}" placeholder="未知" /></div><div class="field"><label>年龄</label><input name="age" value="${e(p.age||'未知')}" placeholder="未知" /></div></div><div class="field"><label>身份</label><input name="identity" value="${e(p.identity||'未知')}" placeholder="未知" /></div><div class="field"><label>外貌</label><textarea name="appearance" placeholder="未知">${e(p.appearance||'未知')}</textarea></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存资料</button></div></form></section></div>`}
function apiModal(){const a=state.modal==='editApi'?api(state.editingId):{};return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${a?.id?'编辑接口':'添加接口'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="interface-form"><div class="field"><label>接口名称</label><input name="name" value="${e(a?.name)}" required placeholder="例如：DeepSeek" /></div><div class="field"><label>接口地址</label><input name="baseUrl" value="${e(a?.baseUrl)}" required placeholder="https://api.example.com/v1" /><small>通常填写到 /v1 即可，也兼容完整的 /models 或 /chat/completions 地址。</small></div><div class="field"><label>API 密钥</label><input name="apiKey" type="password" value="${e(a?.apiKey)}" required placeholder="输入密钥" /></div><div class="switch-row"><div class="switch-copy"><strong>文字分隔兼容模式</strong><p>仅为这个接口开启文字分隔处理。</p></div><button type="button" class="switch ${a?.separator?'on':''}" data-interface-separator></button><input type="hidden" name="separator" value="${a?.separator?'true':'false'}" /></div>${a?.models?.length?`<div class="api-state"><span class="dot"></span>已识别 ${a.models.length} 个模型</div>`:''}<button type="button" class="btn full api-test-button" data-test-api>测试 API 连通性</button><div class="api-test-result" data-api-test-result hidden aria-live="polite"></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存并读取模型</button></div>${a?.id?`<button type="button" class="btn danger full" data-delete-api="${a.id}">${I.trash}删除接口</button>`:''}</form></section></div>`}
function agentModal(){const current=state.modal==='editAgent'?agent(state.editingId):{};const selected=state.agentApiId||current?.apiId||db.apis[0]?.id||'';const source=api(selected),models=source?.models||[];return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${current?.id?'编辑智能体':'创建智能体'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="agent-form"><div class="field"><label>智能体名称</label><input name="name" value="${e(state.agentNameDraft||current?.name)}" required placeholder="例如：剧情对话智能体" /></div><div class="field"><label>选择接口</label><select name="apiId" id="agent-api" required><option value="">请选择</option>${db.apis.map(a=>`<option value="${a.id}" ${selected===a.id?'selected':''}>${e(a.name)}</option>`).join('')}</select></div><div class="field"><label>选择模型</label>${models.length?`<select name="model" required>${models.map(m=>`<option value="${e(m)}" ${current?.model===m?'selected':''}>${e(m)}</option>`).join('')}</select>`:`<input name="model" value="${e(current?.model)}" required placeholder="未识别到列表，可手动填写模型名称" />`}<small>${source?models.length?`已从 ${e(source.name)} 自动读取模型列表。`:'该接口尚未读取到模型，可保存接口重试或手动填写。':'请先添加接口。'}</small></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存智能体</button></div>${current?.id?`<button type="button" class="btn danger full" data-delete-agent="${current.id}">${I.trash}删除智能体</button>`:''}</form></section></div>`}
function groupModal(){return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>创建群聊</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="group-form"><div class="field"><label>群聊名称</label><input name="name" required placeholder="例如：森林调查队" /></div><div class="field"><label>选择成员（至少两位）</label><div class="check-list">${chars().map(c=>`<label class="check-row"><input type="checkbox" name="members" value="${c.id}" /><span>${e(c.name)} · ${e(c.role)}</span></label>`).join('')}</div></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">创建群聊</button></div></form></section></div>`}
function memoryModal(){const existing=state.modal==='editMemory'?db.memories.find(x=>x.id===state.editingId):null,source=db.messages.find(x=>x.id===state.sourceMessageId),contextChat=source?chat(source.chatId):(state.page==='chat'?chat():null),known=existing?.knownBy||contextChat?.memberIds||chars().map(c=>c.id);return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${existing?'编辑故事记忆':'添加故事记忆'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="memory-form"><div class="field"><label>发生了什么</label><textarea name="text" required placeholder="记录值得长期记住的重要事件">${e(existing?.text||source?.text||'')}</textarea></div><div class="field"><label>大概什么时候发生</label><input name="when" value="${e(existing?.when||'刚刚')}" placeholder="例如：今天下午" /></div><div class="field"><label>谁知道这件事</label><div class="check-list">${chars().map(c=>`<label class="check-row"><input type="checkbox" name="knownBy" value="${c.id}" ${known.includes(c.id)?'checked':''}/>${av(c,true)}<span>${e(c.name)}</span></label>`).join('')||'<div class="empty-card">当前故事还没有 AI 人物。</div>'}</div><small>未勾选的人物不会在 AI 对话提示中看到这条记忆。</small></div><input type="hidden" name="sourceChatId" value="${e(existing?.sourceChatId||source?.chatId||contextChat?.id||'')}" /><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存记忆</button></div>${existing?`<button type="button" class="btn danger full" data-delete-memory="${existing.id}">${I.trash}删除记忆</button>`:''}</form></section></div>`}
function messageEditModal(){const m=db.messages.find(x=>x.id===state.editingId);return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>修改消息</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="message-form"><div class="field"><label>消息内容</label><textarea name="text" required>${e(m?.text||'')}</textarea></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存修改</button></div></form></section></div>`}
function sceneSettingsModal(){const c=chat(),scene=c.scene,timeline=db.memories.filter(m=>m.storyId===db.currentStoryId&&m.sourceChatId===c.id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));return`<div class="modal-layer"><section class="modal scene-modal"><div class="modal-handle"></div><div class="modal-head"><div><h2>当前场景</h2><p class="modal-sub">${e(c.name)}</p></div><button class="icon-btn" data-close>×</button></div><form class="form" id="scene-form"><div class="field"><label>环境介绍</label><textarea name="environment" placeholder="例如：黄昏的学院图书馆，窗外正下着雨。">${e(scene.environment||'')}</textarea><small>环境会加入当前聊天中每个角色的对话背景。</small></div><div class="switch-row"><div class="switch-copy"><strong>AI 自动整理当前记忆</strong><p>每轮对话结束后生成一个简短时间节点。</p></div><button type="button" class="switch ${scene.autoMemory?'on':''}" data-scene-auto></button><input type="hidden" name="autoMemory" value="${scene.autoMemory?'true':'false'}" /></div>${scene.lastSummaryError?`<div class="summary-warning">${e(scene.lastSummaryError)}</div>`:''}<button type="button" class="btn full" data-summarize-now>立即总结当前对话</button><button class="btn primary full" type="submit">保存场景设置</button></form><div class="section-head timeline-head"><h2>当前记忆时间线</h2><button class="btn small" data-modal="memory">${I.plus}手动添加</button></div><div class="timeline">${timeline.map((m,i)=>`<article class="timeline-item"><div class="timeline-rail"><i></i>${i<timeline.length-1?'<span></span>':''}</div><div class="timeline-content"><div class="timeline-time">${e(m.when)} · ${m.auto?'AI 总结':'手动记录'}</div><p>${e(m.text)}</p><small>${e(m.knownBy.map(id=>char(id)?.name).filter(Boolean).join('、')||'无人')}知道</small></div><button class="icon-btn memory-edit" data-edit-memory="${m.id}">${I.edit}</button></article>`).join('')||'<div class="empty-card">还没有当前记忆。完成一轮对话后，AI 会在这里生成第一个时间节点。</div>'}</div></section></div>`}
function bubbleActionsModal(){const m=db.messages.find(x=>x.id===state.actionMessageId),a=state.actionAnchor||{x:180,y:300,below:false},pos=`--menu-x:${a.x}px;--menu-y:${a.y}px`;if(state.confirmDelete)return`<div class="modal-layer action-layer" data-dismiss-actions><section class="bubble-menu confirm-menu ${a.below?'menu-below':''}" style="${pos}" role="dialog" aria-label="确认删除消息"><div class="confirm-icon">${I.trash}</div><strong>删除这条消息？</strong><p>此操作只会删除当前气泡，无法撤销。</p><div class="confirm-actions"><button data-bubble-action="cancel-delete">取消</button><button class="confirm-danger" data-bubble-action="confirm-delete">删除</button></div></section></div>`;const copy='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg>',redo='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 7v5h-5"/><path d="M19 12a7 7 0 1 0-1.9 4.8"/></svg>';return`<div class="modal-layer action-layer" data-dismiss-actions><section class="bubble-menu ${a.below?'menu-below':''}" style="${pos}" role="menu" aria-label="消息操作"><div class="bubble-menu-grid"><button data-bubble-action="copy" role="menuitem"><b>${copy}</b><span>复制</span></button><button data-bubble-action="regenerate" role="menuitem"><b>${redo}</b><span>重新生成</span></button><button data-bubble-action="edit" role="menuitem"><b>${I.edit}</b><span>编辑</span></button><button class="danger-action" data-bubble-action="delete" role="menuitem"><b>${I.trash}</b><span>删除</span></button></div></section></div>`}

function render(){const pages={home:homePage,story:storyPage,characters:charactersPage,chat:chatPage,settings:settingsPage,memory:memoriesPage};document.querySelector('#app').innerHTML=(pages[state.page]||homePage)();bind();if(state.page==='chat'){const x=document.querySelector('#messages');if(x)x.scrollTop=x.scrollHeight}}
function go(p){if(p==='story'&&!story())p='home';state.page=p;state.modal=null;render()}
function openPrivate(cid){let c=db.chats.find(x=>x.type==='private'&&x.storyId===db.currentStoryId&&x.memberIds[0]===cid);if(!c){const person=char(cid);c={id:uid('p'),storyId:db.currentStoryId,type:'private',name:person.name,memberIds:[cid],scene:{environment:'',autoMemory:true},updatedAt:now()};db.chats.push(c);save()}state.chatId=c.id;go('chat')}
function formObj(form){return Object.fromEntries(new FormData(form).entries())}
function bind(){
 document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));
 document.querySelectorAll('[data-story]').forEach(x=>x.onclick=()=>{db.currentStoryId=x.dataset.story;save();state.tab='overview';go('story')});
 document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;render()});
 document.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>{state.chatId=x.dataset.chat;go('chat')});
 document.querySelectorAll('[data-private]').forEach(x=>x.onclick=()=>openPrivate(x.dataset.private));
 document.querySelectorAll('[data-modal]').forEach(x=>x.onclick=()=>{state.modal=x.dataset.modal;state.editingId=null;state.sourceMessageId=null;if(state.modal==='agent'){state.agentApiId=db.apis[0]?.id||'';state.agentNameDraft=''}render()});
 document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{state.modal=null;render()});
 document.querySelectorAll('[data-edit-char]').forEach(x=>x.onclick=()=>{state.modal='editCharacter';state.editingId=x.dataset.editChar;render()});
 document.querySelectorAll('[data-edit-story]').forEach(x=>x.onclick=()=>{state.modal='editStory';state.editingId=x.dataset.editStory;render()});
 document.querySelectorAll('[data-edit-api]').forEach(x=>x.onclick=()=>{state.modal='editApi';state.editingId=x.dataset.editApi;render()});
 document.querySelectorAll('[data-edit-agent]').forEach(x=>x.onclick=()=>{const a=agent(x.dataset.editAgent);state.modal='editAgent';state.editingId=a.id;state.agentApiId=a.apiId;state.agentNameDraft='';render()});
 document.querySelectorAll('[data-chat-menu]').forEach(x=>x.onclick=()=>{state.modal='sceneSettings';render()});
 document.querySelectorAll('[data-edit-memory]').forEach(x=>x.onclick=()=>{state.modal='editMemory';state.editingId=x.dataset.editMemory;state.sourceMessageId=null;render()});
 document.querySelectorAll('[data-message-id]').forEach(x=>{x.oncontextmenu=ev=>{ev.preventDefault();openBubbleActions(x.dataset.messageId,x)};let timer,startX=0,startY=0;x.ontouchstart=ev=>{const t=ev.touches[0];startX=t.clientX;startY=t.clientY;timer=setTimeout(()=>{navigator.vibrate?.(18);openBubbleActions(x.dataset.messageId,x)},520)};x.ontouchmove=ev=>{const t=ev.touches[0];if(Math.abs(t.clientX-startX)>8||Math.abs(t.clientY-startY)>8)clearTimeout(timer)};x.ontouchend=x.ontouchcancel=()=>clearTimeout(timer)});
 const sf=document.querySelector('#story-form');if(sf)sf.onsubmit=ev=>{ev.preventDefault();const d=formObj(sf);if(state.editingId){Object.assign(db.stories.find(x=>x.id===state.editingId),d,{updatedAt:now()})}else{const s={id:uid('s'),...d,player:{name:'我',gender:'未知',age:'未知',identity:'未知',appearance:'未知'},theme:['magic','ember','ocean'][db.stories.length%3],updatedAt:now()};db.stories.push(s);db.currentStoryId=s.id}save();state.modal=null;state.tab='overview';go('story');toast('故事已保存')};
 const cf=document.querySelector('#character-form');if(cf)cf.onsubmit=ev=>{ev.preventDefault();const d=formObj(cf);if(state.editingId){Object.assign(char(state.editingId),d);db.chats.filter(x=>x.type==='private'&&x.memberIds[0]===state.editingId).forEach(x=>x.name=d.name)}else{const c={id:uid('c'),storyId:db.currentStoryId,tone:db.characters.length%5,...d};db.characters.push(c);db.chats.push({id:uid('p'),storyId:db.currentStoryId,type:'private',name:c.name,memberIds:[c.id],scene:{environment:'',autoMemory:true},updatedAt:now()})}save();state.modal=null;render();toast('人物已保存')};
 const gf=document.querySelector('#group-form');if(gf)gf.onsubmit=ev=>{ev.preventDefault();const d=formObj(gf),ids=[...gf.querySelectorAll('[name=members]:checked')].map(x=>x.value);if(ids.length<2){toast('请至少选择两位人物');return}const c={id:uid('g'),storyId:db.currentStoryId,type:'group',name:d.name,memberIds:ids,scene:{environment:'',autoMemory:true},updatedAt:now()};db.chats.push(c);save();state.chatId=c.id;state.modal=null;go('chat')};
 const memoryForm=document.querySelector('#memory-form');if(memoryForm)memoryForm.onsubmit=ev=>{ev.preventDefault();const d=formObj(memoryForm);d.knownBy=[...memoryForm.querySelectorAll('[name=knownBy]:checked')].map(x=>x.value);if(state.editingId)Object.assign(db.memories.find(x=>x.id===state.editingId),d);else db.memories.push({id:uid('mem'),storyId:db.currentStoryId,createdAt:now(),...d});save();state.modal=null;state.editingId=null;state.sourceMessageId=null;if(state.page==='story')state.tab='memory';render();toast('故事记忆已保存')};
 const messageForm=document.querySelector('#message-form');if(messageForm)messageForm.onsubmit=ev=>{ev.preventDefault();const m=db.messages.find(x=>x.id===state.editingId);if(m)m.text=formObj(messageForm).text.trim();save();state.modal=null;state.editingId=null;render();toast('消息已修改')};
 const sceneForm=document.querySelector('#scene-form');if(sceneForm)sceneForm.onsubmit=ev=>{ev.preventDefault();const d=formObj(sceneForm);chat().scene.environment=d.environment.trim();chat().scene.autoMemory=d.autoMemory==='true';save();state.modal=null;render();toast('场景设置已保存')};
 const sceneToggle=document.querySelector('[data-scene-auto]');if(sceneToggle)sceneToggle.onclick=()=>{const hidden=document.querySelector('#scene-form [name=autoMemory]');hidden.value=hidden.value==='true'?'false':'true';sceneToggle.classList.toggle('on')};
 const summarizeNow=document.querySelector('[data-summarize-now]');if(summarizeNow)summarizeNow.onclick=async()=>{const c=chat(),recent=msgList().slice(-12);if(!recent.length){toast('当前还没有可以总结的对话');return}state.modal=null;render();await summarizeScene(c,recent,true)};
 document.querySelectorAll('[data-bubble-action]').forEach(x=>x.onclick=()=>handleBubbleAction(x.dataset.bubbleAction));
 const dismiss=document.querySelector('[data-dismiss-actions]');if(dismiss)dismiss.onclick=ev=>{if(ev.target===dismiss){state.modal=null;state.confirmDelete=false;render()}};
 if(state.modal==='bubbleActions')document.onkeydown=ev=>{if(ev.key==='Escape'){state.modal=null;state.confirmDelete=false;render()}};else document.onkeydown=null;
 const pf=document.querySelector('#player-form');if(pf)pf.onsubmit=ev=>{ev.preventDefault();const d=formObj(pf);Object.keys(d).forEach(k=>d[k]=d[k].trim()||'未知');story().player=d;save();state.modal=null;render();toast('我的角色资料已保存')};
 const separator=document.querySelector('[data-interface-separator]');if(separator)separator.onclick=()=>{const hidden=document.querySelector('[name=separator]');hidden.value=hidden.value==='true'?'false':'true';separator.classList.toggle('on')};
 const testApi=document.querySelector('[data-test-api]');if(testApi)testApi.onclick=()=>testApiConnection(document.querySelector('#interface-form'));
 const intf=document.querySelector('#interface-form');if(intf)intf.onsubmit=async ev=>{ev.preventDefault();const d=formObj(intf);d.separator=d.separator==='true';let item;if(state.editingId){item=api(state.editingId);Object.assign(item,d)}else{item={id:uid('api'),models:[],...d};db.apis.push(item)}save();state.modal=null;state.editingId=null;render();toast('正在自动读取模型列表…');await fetchModels(item);render()};
 const agentForm=document.querySelector('#agent-form');if(agentForm)agentForm.onsubmit=ev=>{ev.preventDefault();const d=formObj(agentForm);if(state.editingId)Object.assign(agent(state.editingId),d);else db.agents.push({id:uid('agent'),...d});save();state.modal=null;state.agentApiId='';state.agentNameDraft='';render();toast('智能体已保存')};
 const agentApi=document.querySelector('#agent-api');if(agentApi)agentApi.onchange=async()=>{state.agentNameDraft=document.querySelector('#agent-form [name=name]').value;state.agentApiId=agentApi.value;const source=api(agentApi.value);if(source&&!source.models?.length){toast('正在读取模型列表…');await fetchModels(source,true)}render()};
 document.querySelectorAll('[data-delete-char]').forEach(x=>x.onclick=()=>deleteCharacter(x.dataset.deleteChar));
 document.querySelectorAll('[data-delete-story]').forEach(x=>x.onclick=()=>deleteStory(x.dataset.deleteStory));
 document.querySelectorAll('[data-delete-api]').forEach(x=>x.onclick=()=>deleteApi(x.dataset.deleteApi));
 document.querySelectorAll('[data-delete-agent]').forEach(x=>x.onclick=()=>deleteAgent(x.dataset.deleteAgent));
 document.querySelectorAll('[data-delete-memory]').forEach(x=>x.onclick=()=>deleteMemory(x.dataset.deleteMemory));
 const send=document.querySelector('#send'),comp=document.querySelector('#composer');if(send){send.onclick=()=>sendMessage(comp.value);comp.onkeydown=ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();sendMessage(comp.value)}}}
 document.querySelectorAll('[data-retry]').forEach(x=>x.onclick=()=>{const m=db.messages.find(y=>y.id===x.dataset.retry);if(m){db.messages=db.messages.filter(y=>y.id!==m.id);save();sendMessage(m.original||'请继续回复刚才的话题。')}});
}
function deleteCharacter(id){const c=char(id);if(!c||!confirm(`确定删除“${c.name}”吗？相关私聊记录也会删除。`))return;const chatIds=db.chats.filter(x=>x.memberIds.includes(id)&&(x.type==='private'||x.memberIds.length<=2)).map(x=>x.id);db.messages=db.messages.filter(m=>!chatIds.includes(m.chatId));db.chats=db.chats.filter(x=>!chatIds.includes(x.id)).map(x=>({...x,memberIds:x.memberIds.filter(y=>y!==id)}));db.memories.forEach(m=>m.knownBy=m.knownBy.filter(x=>x!==id));db.characters=db.characters.filter(x=>x.id!==id);save();state.modal=null;render();toast('人物已删除')}
function deleteStory(id){const s=db.stories.find(x=>x.id===id);if(!s||!confirm(`确定删除故事“${s.name}”及其中全部内容吗？`))return;const ids=db.chats.filter(x=>x.storyId===id).map(x=>x.id);db.messages=db.messages.filter(x=>!ids.includes(x.chatId));db.chats=db.chats.filter(x=>x.storyId!==id);db.characters=db.characters.filter(x=>x.storyId!==id);db.memories=db.memories.filter(x=>x.storyId!==id);db.stories=db.stories.filter(x=>x.id!==id);db.currentStoryId=db.stories[0]?.id||'';save();go('home')}
function deleteApi(id){const item=api(id);if(!item||!confirm(`删除接口“${item.name}”吗？使用它的智能体也会删除。`))return;const agentIds=db.agents.filter(x=>x.apiId===id).map(x=>x.id);db.characters.forEach(c=>{if(agentIds.includes(c.agentId))c.agentId=''});db.agents=db.agents.filter(x=>x.apiId!==id);db.apis=db.apis.filter(x=>x.id!==id);save();state.modal=null;render();toast('接口已删除')}
function deleteAgent(id){const item=agent(id);if(!item||!confirm(`删除智能体“${item.name}”吗？`))return;db.characters.forEach(c=>{if(c.agentId===id)c.agentId=''});db.agents=db.agents.filter(x=>x.id!==id);save();state.modal=null;render();toast('智能体已删除')}
function deleteMemory(id){if(!confirm('确定删除这条故事记忆吗？'))return;db.memories=db.memories.filter(m=>m.id!==id);save();state.modal=null;render();toast('故事记忆已删除')}
function openBubbleActions(id,row){if(state.sending)return;const phone=document.querySelector('.phone'),messages=document.querySelector('#messages'),bubble=row?.querySelector('.bubble'),pr=phone?.getBoundingClientRect(),br=bubble?.getBoundingClientRect();let x=180,y=300,below=false;if(pr&&br){x=Math.max(126,Math.min(pr.width-126,br.left-pr.left+br.width/2));below=br.top-pr.top<150;y=below?br.bottom-pr.top+8:br.top-pr.top-8}state.chatScrollTop=messages?.scrollTop??null;state.actionMessageId=id;state.actionAnchor={x,y,below};state.confirmDelete=false;state.modal='bubbleActions';render()}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok}}
async function handleBubbleAction(action){const m=db.messages.find(x=>x.id===state.actionMessageId);if(!m)return;if(action==='copy'){await copyText(m.text);state.modal=null;render();toast('已复制')}else if(action==='edit'){state.modal='editMessage';state.editingId=m.id;render()}else if(action==='delete'){state.confirmDelete=true;render()}else if(action==='cancel-delete'){state.confirmDelete=false;render()}else if(action==='confirm-delete'){db.messages=db.messages.filter(x=>x.id!==m.id);save();state.modal=null;state.confirmDelete=false;render();toast('消息已删除')}else if(action==='regenerate'){state.modal=null;render();await regenerateMessage(m)}}
async function regenerateMessage(target){const c=chat(target.chatId);if(!c)return;if(target.senderId!=='user'){const person=char(target.senderId);if(!person)return;const globalIndex=db.messages.findIndex(x=>x.id===target.id);db.messages.splice(globalIndex,1);state.sending=true;state.typingId=person.id;render();try{const reply=agent(person.agentId)?await requestAI(person,c):mockReply(person,'请重新回复上一条消息。',0);target.text=reply;target.time=timeNow();db.messages.splice(globalIndex,0,target);save();toast('回复已重新生成')}catch(err){db.messages.splice(globalIndex,0,target);save();toast(err.message||'重新生成失败')}state.sending=false;state.typingId=null;render();return}const records=msgList(c.id),index=records.findIndex(x=>x.id===target.id),later=records.slice(index+1);if(later.some(x=>x.senderId==='user')){toast('只能重新生成最近一轮对话');return}db.messages=db.messages.filter(x=>x.chatId!==c.id||!later.some(y=>y.id===x.id));save();const responders=c.type==='private'?c.memberIds.map(char).filter(Boolean):selectResponders(c,target.text);state.sending=true;for(let i=0;i<responders.length;i++){const person=responders[i];state.typingId=person.id;render();try{const reply=agent(person.agentId)?await requestAI(person,c):mockReply(person,target.text,i);db.messages.push({id:uid('m'),chatId:c.id,senderId:person.id,text:reply,time:timeNow()});save()}catch(err){toast(err.message||'重新生成失败');break}}state.sending=false;state.typingId=null;render();await summarizeScene(c,msgList(c.id).slice(index),false,true)}

function timeNow(){return new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}
function splitChinese(text){return text.replace(/[\u3400-\u9fff](?=[\u3400-\u9fff])/g,'$&丨')}
function normalize(text,speaker,targetChat){let out=String(text||'').replace(/丨/g,'').trim(),names=[speaker?.name,'用户',story().player.name,...(targetChat?.memberIds||[]).map(id=>char(id)?.name)].filter(Boolean).map(x=>String(x).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));const prefix=new RegExp(`^\\s*(?:\\*\\*)?(?:${names.join('|')})\\s*[：:]\\s*(?:\\*\\*)?\\s*`);for(let i=0;i<3&&prefix.test(out);i++)out=out.replace(prefix,'');return out.replace(/^\s*["“]|["”]\s*$/g,'').trim()}
function selectResponders(c,text){const members=c.memberIds.map(char).filter(Boolean),mentioned=members.filter(x=>text.includes(x.name));if(mentioned.length)return mentioned.slice(0,2);let score=[...text].reduce((a,x)=>a+x.charCodeAt(0),0)+msgList(c.id).length;let count=/[？?谁]|大家|你们/.test(text)?Math.min(2,members.length):1;if(score%7===0)count=Math.min(3,members.length);const start=score%members.length;return Array.from({length:count},(_,i)=>members[(start+i)%members.length])}
function mockReply(c,text,index){const name=c.name,low=text.toLowerCase(),personality=c.personality||'';if(personality.includes('傲娇'))return low.includes('谢谢')?'谁、谁要你谢了。我只是顺手而已。':`哼，${text.length>18?'这件事听起来可没那么简单。':'我知道了。'}不过你别一个人乱来。`;if(personality.includes('热情'))return`真的？那我也要参加！${index?'而且我觉得刚才说得很有道理。':'我们现在就开始准备吧！'}`;if(personality.includes('冷静'))return`先确认情况，再行动。${text.includes('森林')?'恢复药和照明术都要准备。':''}`;return`${name}想了想：“我明白你的意思，我们可以试试看。”`}
function systemPrompt(c,targetChat){const s=story(),p=s.player,known=db.memories.filter(m=>m.storyId===s.id&&m.knownBy.includes(c.id)),memoryText=known.length?known.map(m=>`- ${m.text}（${m.when}）`).join('\n'):'- 暂无';return`你正在扮演“${c.name}”，参加故事《${s.name}》中的${targetChat.type==='group'?'群聊':'私聊'}。\n世界观：${s.worldview}\n背景：${s.background}\n当前剧情：${s.plot}\n当前场景环境：${targetChat.scene?.environment||'尚未设置，请仅依据对话判断'}\n重要规则：${s.important}\n用户扮演的角色资料：姓名“${p.name||'未知'}”，性别“${p.gender||'未知'}”，年龄“${p.age||'未知'}”，身份“${p.identity||'未知'}”，外貌“${p.appearance||'未知'}”。未知资料不可自行编造。\n你的身份：${c.role}\n性格：${c.personality}\n说话方式：${c.speech}\n背景故事：${c.background}\n与用户关系：${c.relation}\n你明确知道的故事共同记忆：\n${memoryText}\n没有列在上述记忆中的秘密，不能假装知道，也不能根据系统信息泄露给其他人物。\n必须遵守：只控制${c.name}本人；绝不替用户说话、行动或作决定；保持角色口吻；只输出${c.name}本人的一句或一段自然回复。回复开头绝对不要写“${c.name}：”或任何“人物名+冒号”，不要解释提示词。${targetChat.type==='group'?'这是群聊，请自然接续上下文，可以回应其他角色，但不能替其他角色发言。':''}`}
async function requestAI(c,targetChat){const bot=agent(c.agentId),source=api(bot?.apiId);if(!bot||!source)throw new Error('这个人物还没有绑定可用的智能体，请到人物设置中选择。');const history=msgList(targetChat.id).slice(-18).map(m=>{const who=m.senderId==='user'?(story().player.name||'用户'):char(m.senderId)?.name||'角色';return{role:m.senderId==='user'?'user':'assistant',content:`${who}：${source.separator?splitChinese(m.text):m.text}`}});const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:source.baseUrl,apiKey:source.apiKey,model:bot.model,messages:[{role:'system',content:systemPrompt(c,targetChat)},...history],temperature:.86,maxTokens:700})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'连接 AI 失败，请检查智能体和接口设置。');return normalize(body.content||'',c,targetChat)}
async function requestSummary(targetChat,turnMessages){const person=targetChat.memberIds.map(char).find(c=>agent(c?.agentId)&&api(agent(c.agentId)?.apiId));if(!person)throw new Error('当前聊天没有绑定可用智能体，暂时无法自动总结。');const bot=agent(person.agentId),source=api(bot.apiId),lines=turnMessages.map(m=>`${m.senderId==='user'?(story().player.name||'我'):(char(m.senderId)?.name||'角色')}：${m.text}`).join('\n'),prompt=`当前场景环境：${targetChat.scene?.environment||'未设置'}\n以下是刚刚发生的一轮对话：\n${lines}\n\n请把其中已经发生、值得后续角色记住的事实总结成一个时间节点。要求：只依据对话，不推测未来，不添加未发生的事件；使用第三人称；中文40字以内；只输出总结正文，不要标题，不要“记忆：”前缀。`;const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:source.baseUrl,apiKey:source.apiKey,model:bot.model,messages:[{role:'system',content:'你是严谨的故事记忆整理器，只记录已经发生的事实。'},{role:'user',content:source.separator?splitChinese(prompt):prompt}],temperature:.25,maxTokens:160})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'自动总结失败。');return String(body.content||'').replace(/丨/g,'').replace(/^\s*(?:当前记忆|记忆|总结)\s*[：:]\s*/,'').trim()}
async function summarizeScene(targetChat,turnMessages,manual=false,replaceLatest=false){if(!manual&&!targetChat.scene?.autoMemory)return false;state.summarizing=true;render();try{const summary=await requestSummary(targetChat,turnMessages);if(!summary)throw new Error('智能体没有返回记忆总结。');if(replaceLatest){const latest=db.memories.filter(m=>m.sourceChatId===targetChat.id&&m.auto).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];if(latest)db.memories=db.memories.filter(m=>m.id!==latest.id)}db.memories.push({id:uid('mem'),storyId:targetChat.storyId,text:summary,when:`今天 ${timeNow()}`,knownBy:[...targetChat.memberIds],sourceChatId:targetChat.id,createdAt:now(),auto:true});targetChat.scene.lastSummaryError='';save();if(manual)toast('已生成新的当前记忆');return true}catch(err){targetChat.scene.lastSummaryError=err.message||'自动总结失败';save();if(manual)toast(targetChat.scene.lastSummaryError);return false}finally{state.summarizing=false;render()}}
async function sendMessage(raw){const text=String(raw||'').trim();if(!text||state.sending)return;const c=chat();if(!c)return;const turn=[];const userMessage={id:uid('m'),chatId:c.id,senderId:'user',text,time:timeNow()};db.messages.push(userMessage);turn.push(userMessage);c.updatedAt=now();story().updatedAt=now();save();state.sending=true;render();const responders=c.type==='private'?c.memberIds.map(char).filter(Boolean):selectResponders(c,text);for(let i=0;i<responders.length;i++){const person=responders[i],useAI=!!agent(person.agentId);state.typingId=person.id;render();await new Promise(r=>setTimeout(r,useAI?350:700+i*220));try{const reply=useAI?await requestAI(person,c):mockReply(person,text,i),answer={id:uid('m'),chatId:c.id,senderId:person.id,text:reply,time:timeNow()};db.messages.push(answer);turn.push(answer);save()}catch(err){db.messages.push({id:uid('err'),chatId:c.id,senderId:person.id,text:err.message||'这条消息没有成功发送。',time:timeNow(),error:true,original:text});save();break}state.typingId=null;render()}state.sending=false;state.typingId=null;render();if(turn.length>1)await summarizeScene(c,turn)}
async function fetchModels(source,silent=false){try{const res=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:source.baseUrl,apiKey:source.apiKey})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'模型列表读取失败。');source.models=body.models||[];save();if(!silent)toast(source.models.length?`已识别 ${source.models.length} 个模型`:'接口没有返回模型，可在智能体中手动填写')}catch(err){if(!silent)toast(location.protocol==='file:'?'请通过启动脚本打开应用':(err.message||'读取模型失败'));return false}return true}
async function testApiConnection(form){const button=form?.querySelector('[data-test-api]'),result=form?.querySelector('[data-api-test-result]'),d=form?formObj(form):{};if(!d.baseUrl?.trim()||!d.apiKey?.trim()){result.hidden=false;result.className='api-test-result error';result.textContent='请先填写接口地址和 API 密钥。';return}button.disabled=true;button.textContent='正在测试连接…';result.hidden=false;result.className='api-test-result testing';result.textContent='正在识别聊天地址并验证密钥…';try{const res=await fetch('/api/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:d.baseUrl.trim(),apiKey:d.apiKey.trim()})});let body={};try{body=await res.json()}catch{}if(res.status===404&&body.error?.includes('请求地址不存在'))throw new Error('当前仍是旧版本地服务。请关闭原来的黑色命令窗口，再重新双击 start-storyverse.bat。');if(!res.ok)throw Object.assign(new Error(body.error||'测试请求失败。'),{endpoint:body.endpoint,probeEndpoint:body.probeEndpoint});result.className=`api-test-result ${body.level||'success'}`;result.innerHTML=`<strong>${e(body.message||'连接成功。')}</strong>${body.endpoint?`<small>实际聊天地址：${e(body.endpoint)}</small>`:''}${body.probeEndpoint?`<small>模型验证地址：${e(body.probeEndpoint)}</small>`:''}`}catch(err){result.className='api-test-result error';result.innerHTML=`<strong>${e(location.protocol==='file:'?'请通过 start-storyverse.bat 启动后再测试。':(err.message||'连接测试失败。'))}</strong>${err.endpoint?`<small>已识别聊天地址：${e(err.endpoint)}</small>`:''}${err.probeEndpoint?`<small>模型验证地址：${e(err.probeEndpoint)}</small>`:''}`}finally{button.disabled=false;button.textContent='重新测试 API 连通性'}}

async function runSelfTest(){
 const original=localStorage.getItem(KEY),originalFetch=window.fetch,checks=[];const ok=(name,value)=>{if(!value)throw new Error(name);checks.push('PASS '+name)};
 try{
 db=migrate(structuredClone(seed));save();
  let legacy=structuredClone(seed);delete legacy.apis;delete legacy.agents;delete legacy.stories[0].player;legacy.api={name:'旧接口',baseUrl:'https://legacy.example/v1',apiKey:'key',model:'old-model'};legacy=migrate(legacy);ok('旧数据自动迁移',legacy.stories[0].player.name==='我'&&legacy.apis.length===1&&legacy.agents.length===1);
  state.modal='story';render();let f=document.querySelector('#story-form');f.elements.name.value='自动测试故事';f.elements.summary.value='测试简介';f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
  const sid=db.currentStoryId;ok('创建故事和默认我的角色',db.stories.some(x=>x.id===sid&&x.name==='自动测试故事'&&x.player?.name==='我'&&x.player?.gender==='未知'));
  db.apis.push({id:'test-api',name:'测试接口',baseUrl:'https://example.invalid/v1',apiKey:'test',models:['model-a'],separator:false});state.modal='agent';state.agentApiId='test-api';render();f=document.querySelector('#agent-form');f.elements.name.value='测试智能体';f.elements.model.value='model-a';f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));ok('多接口与智能体数据',db.apis.length===1&&db.agents.some(x=>x.model==='model-a'));state.modal='editApi';state.editingId='test-api';render();ok('API 连通性测试入口',!!document.querySelector('[data-test-api]')&&!!document.querySelector('[data-api-test-result]'));
  for(const name of ['测试甲','测试乙']){state.modal='character';state.editingId=null;render();f=document.querySelector('#character-form');f.elements.name.value=name;f.elements.role.value='测试人物';f.elements.personality.value=name==='测试甲'?'热情':'冷静';f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}
  const created=chars(sid);ok('创建人物及自动私聊',created.length===2&&chats(sid).filter(x=>x.type==='private').length===2);created[0].agentId=db.agents[0].id;
  state.modal='memory';state.editingId=null;state.sourceMessageId=null;render();f=document.querySelector('#memory-form');f.elements.text.value='测试甲知道一条秘密';f.querySelectorAll('[name=knownBy]').forEach((x,i)=>x.checked=i===0);f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));const privateChat=chats(sid).find(x=>x.type==='private');ok('谁知道某条记忆',systemPrompt(created[0],privateChat).includes('测试甲知道一条秘密')&&!systemPrompt(created[1],privateChat).includes('测试甲知道一条秘密'));
  ok('清理人物名前缀',normalize(`${created[0].name}：你好`,created[0],privateChat)==='你好');
  state.modal='group';render();f=document.querySelector('#group-form');f.elements.name.value='测试群聊';f.querySelectorAll('[name=members]').forEach(x=>x.checked=true);f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
  const gid=state.chatId;ok('创建群聊',chat(gid)?.memberIds.length===2);
  window.fetch=async(_url,opt)=>{const req=JSON.parse(opt.body);return{ok:true,json:async()=>({content:req.maxTokens===160?'测试成员约定一起准备出发。':'好的，我们已经准备好了。'})}};
  await sendMessage('大家准备好了吗？');ok('群聊自然回复与记录保存',msgList(gid).filter(x=>x.senderId!=='user').length>=1&&JSON.parse(localStorage.getItem(KEY)).messages.length===db.messages.length);ok('AI 自动生成当前记忆',db.memories.some(x=>x.sourceChatId===gid&&x.auto&&x.knownBy.length===2));
  state.modal='sceneSettings';render();ok('右上角当前场景与记忆时间线',!!document.querySelector('#scene-form,.scene-summary')&&!!document.querySelector('.timeline'));
  const bubble=msgList(gid)[0];state.actionMessageId=bubble.id;state.actionAnchor={x:180,y:300,below:false};state.modal='bubbleActions';render();ok('气泡四项操作菜单',document.querySelectorAll('[data-bubble-action]').length===4&&!!document.querySelector('[data-bubble-action="regenerate"]'));
  if(typeof enterCafe==='function'){enterCafe(created[0].id);const cafe=chats(sid).find(x=>x.type==='scene'&&x.name==='咖啡厅');ok('私聊进入咖啡厅与固定 NPC',!!cafe&&cafe.scene.presentCharacterIds.includes(created[0].id)&&cafe.scene.npcIds.some(id=>npc(id)?.name==='店长')&&msgList(cafe.id).some(m=>npc(m.senderId)?.name==='店长'))}
  document.querySelector('#app').innerHTML=`<pre id="selftest" style="color:#8fffcf;padding:30px;white-space:pre-wrap">${checks.join('\n')}\nALL TESTS PASSED</pre>`;
 }catch(err){document.querySelector('#app').innerHTML=`<pre id="selftest" style="color:#ff9cab;padding:30px">SELF TEST FAILED\n${e(err.message)}</pre>`}
 finally{window.fetch=originalFetch;if(original===null)localStorage.removeItem(KEY);else localStorage.setItem(KEY,original)}
}

if(params.get('selftest')==='1')runSelfTest();else render();
