/* StoryVerse World UI v3 — incremental layer over the stable v2 core. */
const V2={modal:window.modal,bind:window.bind,deleteCharacter:window.deleteCharacter,deleteStory:window.deleteStory,regenerateMessage:window.regenerateMessage};

function migrateWorldV3(){
 db.npcs=Array.isArray(db.npcs)?db.npcs:[];
 db.stories.forEach(s=>{s.lastChatId??=chats(s.id)[0]?.id||'';s.cover??=s.theme||'magic'});
 db.chats.forEach(c=>{
  if(c.type==='group')c.type='scene';
  if(c.type==='scene'){
   const old=c.scene||{};
   c.scene={description:old.description??old.environment??'',status:old.status??'场景持续存在',allowedCharacterIds:Array.isArray(old.allowedCharacterIds)?old.allowedCharacterIds:[...(c.memberIds||[])],presentCharacterIds:Array.isArray(old.presentCharacterIds)?old.presentCharacterIds:[...(c.memberIds||[])],npcIds:Array.isArray(old.npcIds)?old.npcIds:[],autoMemory:old.autoMemory!==false,lastSummaryError:old.lastSummaryError||''};
   c.memberIds=[...c.scene.presentCharacterIds];
  }else c.scene={...(c.scene||{}),environment:c.scene?.environment||'',autoMemory:c.scene?.autoMemory!==false};
 });
 db.memories.forEach(m=>{m.sceneId??=(chat(m.sourceChatId)?.type==='scene'?m.sourceChatId:'')});
 db.schemaVersion=3;save();
}
migrateWorldV3();

const npc=id=>db.npcs.find(x=>x.id===id);
const storyNpcs=(sid=db.currentStoryId)=>db.npcs.filter(x=>x.storyId===sid);
const actor=id=>char(id)||npc(id);
const sceneChats=(sid=db.currentStoryId)=>chats(sid).filter(x=>x.type==='scene');
const privateChats=(sid=db.currentStoryId)=>chats(sid).filter(x=>x.type==='private');
const isScene=c=>c?.type==='scene';
const presentActors=c=>isScene(c)?[...(c.scene.presentCharacterIds||[]).map(char),...(c.scene.npcIds||[]).map(npc)].filter(Boolean):(c?.memberIds||[]).map(char).filter(Boolean);
const sceneIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 20h16M6 20V9l6-5 6 5v11M9 20v-6h6v6"/><path d="M8 9h8"/></svg>';
const chevron='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>';
const down='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m7 10 5 5 5-5"/></svg>';
const coffee='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 8h13v6a6 6 0 0 1-6 6H10a6 6 0 0 1-6-6V8Z"/><path d="M17 10h2a3 3 0 0 1 0 6h-3M7 4c0 1 1 1 1 2m4-2c0 1 1 1 1 2"/></svg>';

window.nav=function(active){return`<nav class="bottom-nav v3-nav"><button data-go="home" class="${active==='home'?'active':''}">${I.home}<span>故事</span></button><button data-go="chats" class="${active==='chats'?'active':''}">${I.chat}<span>聊天</span></button><button data-go="settings" class="${active==='settings'?'active':''}">${I.settings}<span>设置</span></button></nav>`};
window.shell=function(body,bar='',active='home',fab=''){return`<div class="desktop-stage"><div class="phone world-v3">${bar}${body}${fab}${nav(active)}<div class="toast"></div>${modal()}</div></div>`};
window.appbar=function(title,sub='',backTo='',action=''){return`<header class="appbar compact-bar"><div class="appbar-left">${backTo?`<button class="back" data-go="${backTo}">${I.back}</button>`:''}<div><div class="appbar-title">${e(title)}</div>${sub?`<div class="appbar-sub">${e(sub)}</div>`:''}</div></div>${action||'<span class="bar-spacer"></span>'}</header>`};

function storyCover(s,large=false){return`<div class="story-cover cover-${e(s.cover||s.theme||'magic')} ${large?'large':''}"><span>✦</span></div>`}
function compactChatRows(limit=99){return chats().slice(0,limit).map(c=>{const first=char(c.memberIds?.[0]),scene=isScene(c);return`<button class="chat-list-row" data-chat="${c.id}">${scene?`<div class="place-avatar">${sceneIcon}</div>`:av(first)}<div class="list-main"><div class="list-title-line"><strong>${e(c.name)}</strong><span class="type-tag ${scene?'scene-tag':''}">${scene?'场景':'私聊'}</span></div><p>${e(latest(c))}</p></div><time>${fmtTime(c.updatedAt)}</time></button>`}).join('')||'<div class="quiet-empty">这个故事还没有聊天。</div>'}

window.homePage=function(){return shell(`<main class="screen app-screen"><div class="page-heading"><div><h1>我的故事</h1><p>${db.stories.length} 个持续存在的世界</p></div><button class="top-create" data-modal="story">${I.plus}<span>创建</span></button></div><div class="world-list">${db.stories.map(s=>{const sc=db.chats.filter(c=>c.storyId===s.id&&c.type==='scene').length;return`<button class="world-row" data-story="${s.id}">${storyCover(s)}<div><strong>${e(s.name)}</strong><p>${e(s.summary)}</p><small>${chars(s.id).length} 位人物 · ${sc} 个场景 · ${fmtTime(s.updatedAt)}</small></div>${chevron}</button>`}).join('')||'<div class="quiet-empty">创建第一个故事世界吧。</div>'}</div></main>`,appbar('StoryVerse','你的故事世界'),'home')};

function storyManageGrid(){return`<div class="manage-grid"><button data-go="characters">${I.users}<span>人物</span><small>${chars().length} 位</small></button><button data-go="scenes">${sceneIcon}<span>场景</span><small>${sceneChats().length} 个</small></button><button data-go="memory">${I.memory}<span>记忆</span><small>${db.memories.filter(m=>m.storyId===db.currentStoryId).length} 条</small></button><button data-story-menu>${I.more}<span>故事设置</span><small>设定与操作</small></button></div>`}
window.storyPage=function(){const s=story(),recentMem=db.memories.filter(m=>m.storyId===s.id).slice(-2).reverse(),people=chars().slice(0,5),places=sceneChats().slice(0,3),last=chat(s.lastChatId)||chats()[0];return shell(`<main class="screen story-home"><section class="world-hero cover-${e(s.cover||s.theme||'magic')}"><div class="hero-shade"></div><div class="world-hero-copy"><span>当前故事</span><h1>${e(s.name)}</h1><p>${e(s.plot||s.summary)}</p></div></section>${storyManageGrid()}<section class="plain-section"><div class="section-head compact"><h2>主要人物</h2><button data-go="characters">全部</button></div><div class="people-strip">${people.map(c=>`<button data-private="${c.id}">${av(c)}<span>${e(c.name)}</span></button>`).join('')||'<span class="muted-copy">尚未创建人物</span>'}</div></section><section class="plain-section"><div class="section-head compact"><h2>场景</h2><button data-go="scenes">管理</button></div><div class="mini-place-list">${places.map(c=>`<button data-chat="${c.id}"><span>${sceneIcon}</span><div><strong>${e(c.name)}</strong><small>${e(c.scene.status||'等待故事发生')}</small></div>${chevron}</button>`).join('')||'<p class="muted-copy">还没有场景，可以从场景页创建。</p>'}</div></section><section class="plain-section"><div class="section-head compact"><h2>最近记忆</h2><button data-go="memory">查看</button></div>${recentMem.map(m=>`<div class="recent-memory"><i></i><div><p>${e(m.text)}</p><small>${e(m.when)}</small></div></div>`).join('')||'<p class="muted-copy">故事尚未留下长期记忆。</p>'}</section>${last?`<button class="continue-chat" data-chat="${last.id}"><span>${I.chat}</span><div><small>继续上一次聊天</small><strong>${e(last.name)}</strong></div>${chevron}</button>`:''}</main>`,appbar(s.name,'故事主页','home',`<button class="bar-action" data-story-menu>${I.more}</button>`),'home')};

window.charactersPage=function(){const p=story().player;return shell(`<main class="screen compact-screen"><div class="section-head first compact"><h2>故事人物</h2><button class="mini-create" data-modal="character">${I.plus} 创建</button></div><button class="person-list-row player-row" data-modal="player"><div class="avatar tone-4">我</div><div><strong>${e(p.name||'我')}</strong><p>${e(p.identity||'未知身份')} · ${e(p.gender||'未知')} · ${e(p.age||'未知')}</p></div>${chevron}</button><div class="simple-list">${chars().map(c=>{const a=agent(c.agentId);return`<div class="person-list-row">${av(c)}<button class="person-open" data-private="${c.id}"><strong>${e(c.name)}</strong><p>${e(c.role||'未设置身份')}</p><small>${a?'已绑定 '+e(a.name):'使用示例回复'}</small></button><button class="row-edit" data-edit-char="${c.id}">${I.edit}</button></div>`}).join('')||'<div class="quiet-empty">还没有人物。</div>'}</div></main>`,appbar('人物',story().name,'story'),'home')};

window.memoriesPage=function(){return shell(`<main class="screen compact-screen"><div class="section-head first compact"><h2>故事记忆</h2><button class="mini-create" data-modal="memory">${I.plus} 添加</button></div><p class="inline-note">只有被标记为知情的人物或 NPC 才会获得对应记忆。</p>${memoryContent()}</main>`,appbar('记忆',story().name,'story'),'home')};

window.chatsPage=function(){return shell(`<main class="screen chat-index"><button class="story-selector" data-story-switch><span>${storyCover(story())}</span><div><small>当前故事</small><strong>${e(story().name)}</strong></div>${down}</button><div class="section-head compact"><h2>最近聊天</h2><button class="mini-create" data-modal="group">${I.plus} 场景</button></div><div class="chat-list">${compactChatRows()}</div></main>`,appbar('聊天','私聊与故事场景'),'chats')};

window.scenesPage=function(){return shell(`<main class="screen compact-screen"><div class="section-head first compact"><h2>故事场景</h2><button class="mini-create" data-modal="group">${I.plus} 创建</button></div><p class="inline-note">场景是持续存在的地点。允许进入，不代表当前在场。</p><div class="scene-list">${sceneChats().map(c=>`<button class="scene-row" data-chat="${c.id}"><div class="place-avatar">${sceneIcon}</div><div><strong>${e(c.name)}</strong><p>${e(c.scene.description||'尚未填写场景介绍')}</p><small>${(c.scene.presentCharacterIds||[]).length+1} 人在场 · ${(c.scene.npcIds||[]).length} 位固定 NPC</small></div>${chevron}</button>`).join('')||'<div class="quiet-empty">还没有场景。</div>'}</div></main>`,appbar('场景',story().name,'story'),'home')};

function settingRow(icon,title,copy,key,count=''){return`<button class="setting-row" data-setting-section="${key}"><span class="setting-icon">${icon}</span><div><strong>${title}</strong><p>${copy}</p></div>${count?`<small>${count}</small>`:''}${chevron}</button>`}
window.settingsPage=function(){if(state.settingsView==='ai')return aiSettingsPage();return shell(`<main class="screen compact-screen"><div class="settings-group"><h2>AI 与模型</h2>${settingRow('API','AI 接口','连接和测试 OpenAI 兼容服务','ai',db.apis.length+' 个')}${settingRow('AI','智能体与模型','管理人物使用的模型','ai',db.agents.length+' 个')}</div><div class="settings-group"><h2>应用</h2>${settingRow(I.chat,'聊天设置','回复、记忆与输入偏好','placeholder')}${settingRow('◐','外观','深色主题与显示密度','placeholder')}${settingRow('↕','数据','备份、导入与本地存储','placeholder')}${settingRow('⌁','高级设置','兼容模式与调试选项','placeholder')}</div><div class="settings-group"><h2>关于</h2>${settingRow('✦','关于 StoryVerse','持续存在的 AI 故事世界','about','','')}</div></main>`,appbar('设置','全局应用设置'),'settings')}
function aiSettingsPage(){return shell(`<main class="screen compact-screen"><div class="section-head first compact"><h2>AI 接口</h2><button class="mini-create" data-modal="api">${I.plus} 添加</button></div><div class="simple-list">${db.apis.map(a=>`<button class="setting-row" data-edit-api="${a.id}"><span class="setting-icon">API</span><div><strong>${e(a.name)}</strong><p>${e(a.baseUrl)}</p></div><small>${a.models?.length||0} 模型</small>${chevron}</button>`).join('')||'<div class="quiet-empty">还没有接口。</div>'}</div><div class="section-head compact"><h2>智能体与模型</h2><button class="mini-create" data-modal="agent">${I.plus} 创建</button></div><div class="simple-list">${db.agents.map(a=>`<button class="setting-row" data-edit-agent="${a.id}"><span class="setting-icon agent">AI</span><div><strong>${e(a.name)}</strong><p>${e(api(a.apiId)?.name||'接口已删除')} · ${e(a.model)}</p></div>${chevron}</button>`).join('')||'<div class="quiet-empty">还没有智能体。</div>'}</div></main>`,appbar('AI 与模型','全局设置','settings'),'settings')}

function sceneHeader(c){const count=presentActors(c).length+1;return`<header class="chat-header v3-chat-header"><button class="back" data-go="chats">${I.back}</button><div class="chat-title"><strong>${e(c.name)}</strong><button data-story-switch>${e(story().name)} ${down}</button></div><button class="bar-action" data-chat-menu>${I.more}</button><div class="presence-line">${count} 人在场</div></header>`}
window.chatPage=function(){const c=chat();if(!c){state.page='chats';return chatsPage()}if(c.storyId!==db.currentStoryId){db.currentStoryId=c.storyId;save()}story().lastChatId=c.id;save();const people=presentActors(c);return`<div class="desktop-stage"><div class="phone world-v3"><section class="chat-shell">${isScene(c)?sceneHeader(c):`<header class="chat-header v3-chat-header private-head"><button class="back" data-go="chats">${I.back}</button>${av(people[0])}<div class="chat-title"><strong>${e(c.name)}</strong><button data-story-switch>${e(story().name)} ${down}</button></div><button class="bar-action" data-chat-menu>${I.more}</button></header>`}<div class="messages" id="messages"><div class="day">今天</div>${msgList().map((m,i,a)=>messageHtml(m,i===a.length-1)).join('')}${state.typingId?`<div class="typing"><span class="dots"><i></i><i></i><i></i></span>${e(actor(state.typingId)?.name||'角色')}正在输入…</div>`:''}${state.summarizing?`<div class="typing summary-typing">正在整理当前记忆…</div>`:''}</div><div class="composer-area"><div class="composer"><textarea id="composer" rows="1" placeholder="说点什么…" ${state.sending?'disabled':''}></textarea><button class="send" id="send" ${state.sending?'disabled':''}>${I.send}</button></div></div></section><div class="toast"></div>${modal()}</div></div>`}
window.messageHtml=function(m,isLast=false){const a=m.senderId==='user'?null:actor(m.senderId),display=m.senderId==='user'||m.error?m.text:normalize(m.text,a,chat(m.chatId));return`<div class="message ${m.senderId==='user'?'mine':''} ${state.modal==='bubbleActions'&&state.actionMessageId===m.id?'message-selected':''}" data-message-id="${m.id}">${m.senderId==='user'?'':av(a,true)}<div class="message-content"><div class="sender">${m.senderId==='user'?'我':e(a?.name||'未知人物')}${a?.isNpc?'<span>NPC</span>':''}</div><div class="bubble ${m.error?'error-bubble':''}">${e(display)}</div><div class="msg-time">${e(m.time||'')}</div>${m.error?`<button class="retry" data-retry="${m.id}">重新发送</button>`:''}${isLast?journeyCard(m):''}</div></div>`}
function journeyCard(m){const c=chat(m.chatId);if(c?.type!=='private'||m.senderId==='user')return'';const recent=msgList(c.id).slice(-4).findLast?.(x=>x.senderId==='user')||[...msgList(c.id).slice(-4)].reverse().find(x=>x.senderId==='user');if(!recent||!/(咖啡|喝一杯|喝点)/.test(recent.text))return'';return`<button class="journey-card" data-enter-cafe="${m.senderId}">${coffee}<span><small>一起前往</small><strong>咖啡厅</strong></span>${chevron}</button>`}

function storySwitcherModal(){return`<div class="modal-layer"><section class="modal compact-modal"><div class="modal-handle"></div><div class="modal-head"><h2>切换故事</h2><button class="icon-btn" data-close>×</button></div><div class="switch-story-list">${db.stories.map(s=>`<button data-switch-story="${s.id}" class="${s.id===db.currentStoryId?'selected':''}">${storyCover(s)}<div><strong>${e(s.name)}</strong><p>${e(s.plot||s.summary)}</p></div>${s.id===db.currentStoryId?'<i>当前</i>':chevron}</button>`).join('')}</div></section></div>`}
function storyMenuModal(){return`<div class="modal-layer"><section class="modal compact-modal"><div class="modal-handle"></div><div class="modal-head"><h2>${e(story().name)}</h2><button class="icon-btn" data-close>×</button></div><div class="action-list"><button data-edit-story="${story().id}">${I.edit}<span>编辑故事与设定</span>${chevron}</button><button data-go="memory">${I.memory}<span>记忆管理</span>${chevron}</button><button data-export-story>${I.home}<span>导出故事数据</span>${chevron}</button><button class="danger-row" data-delete-story="${story().id}">${I.trash}<span>删除故事</span>${chevron}</button></div></section></div>`}
window.groupModal=function(){return sceneEditorModal()}
function sceneEditorModal(){const c=state.modal==='editScene'?chat(state.editingId):null,s=c?.scene||{},allowed=s.allowedCharacterIds||[],present=s.presentCharacterIds||[],fixed=(s.npcIds||[]).map(npc).filter(Boolean);return`<div class="modal-layer"><section class="modal scene-editor"><div class="modal-handle"></div><div class="modal-head"><h2>${c?'编辑场景':'创建场景'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="v3-scene-form"><div class="field"><label>场景名称</label><input name="name" value="${e(c?.name)}" required placeholder="例如：咖啡厅" /></div><div class="field"><label>场景介绍</label><textarea name="description" placeholder="这里是什么地方？">${e(s.description)}</textarea></div><div class="field"><label>当前状态</label><input name="status" value="${e(s.status)}" placeholder="例如：傍晚，店里客人不多" /></div><div class="field"><label>允许进入的人物</label><div class="check-list compact-checks">${chars().map(x=>`<label class="check-row"><input type="checkbox" name="allowed" value="${x.id}" ${allowed.includes(x.id)?'checked':''}/>${av(x,true)}<span>${e(x.name)}</span></label>`).join('')}</div></div><div class="field"><label>当前在场人物</label><div class="check-list compact-checks">${chars().map(x=>`<label class="check-row"><input type="checkbox" name="present" value="${x.id}" ${present.includes(x.id)?'checked':''}/>${av(x,true)}<span>${e(x.name)}</span></label>`).join('')}</div><small>“我”默认始终在当前打开的场景中。</small></div><div class="field"><label>固定 NPC</label><input name="npcName" value="${e(fixed[0]?.name)}" placeholder="例如：店长（第一版支持一位）" /></div><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">${c?'保存':'创建场景'}</button></div></form></section></div>`}
window.sceneSettingsModal=function(){const c=chat();if(!isScene(c))return privateSettingsModal(c);const s=c.scene,timeline=db.memories.filter(m=>m.storyId===c.storyId&&m.sourceChatId===c.id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));return`<div class="modal-layer"><section class="modal scene-modal"><div class="modal-handle"></div><div class="modal-head"><div><h2>${e(c.name)}</h2><p class="modal-sub">场景设置与当前记忆</p></div><button class="icon-btn" data-close>×</button></div><div class="scene-summary"><p>${e(s.description||'尚未填写场景介绍')}</p><small>${e(s.status||'尚未设置当前状态')}</small><div><span>允许 ${(s.allowedCharacterIds||[]).length} 人</span><span>当前在场 ${(s.presentCharacterIds||[]).length+1} 人</span><span>${(s.npcIds||[]).length} NPC</span></div></div><button class="btn full" data-edit-scene="${c.id}">${I.edit} 编辑场景成员与设定</button><div class="switch-row"><div class="switch-copy"><strong>AI 自动整理当前记忆</strong><p>每轮对话后生成时间节点。</p></div><button type="button" class="switch ${s.autoMemory?'on':''}" data-scene-auto></button></div>${s.lastSummaryError?`<div class="summary-warning">${e(s.lastSummaryError)}</div>`:''}<button class="btn full" data-summarize-now>立即总结当前对话</button><div class="section-head timeline-head compact"><h2>场景记忆</h2><button class="mini-create" data-modal="memory">${I.plus} 添加</button></div><div class="timeline">${timeline.map((m,i)=>`<article class="timeline-item"><div class="timeline-rail"><i></i>${i<timeline.length-1?'<span></span>':''}</div><div class="timeline-content"><div class="timeline-time">${e(m.when)} · ${m.auto?'AI 总结':'手动'}</div><p>${e(m.text)}</p><small>${e(m.knownBy.map(id=>actor(id)?.name).filter(Boolean).join('、')||'无人')}知道</small></div><button class="icon-btn memory-edit" data-edit-memory="${m.id}">${I.edit}</button></article>`).join('')||'<div class="quiet-empty">这里还没有场景记忆。</div>'}</div></section></div>`}
function privateSettingsModal(c){return`<div class="modal-layer"><section class="modal compact-modal"><div class="modal-handle"></div><div class="modal-head"><h2>${e(c.name)} · 私聊</h2><button class="icon-btn" data-close>×</button></div><p class="inline-note">私聊与当前故事共享人物关系和知情记忆。</p><button class="btn full" data-modal="memory">${I.memory} 添加故事记忆</button></section></div>`}
window.memoryModal=function(){const existing=state.modal==='editMemory'?db.memories.find(x=>x.id===state.editingId):null,source=db.messages.find(x=>x.id===state.sourceMessageId),context=source?chat(source.chatId):(state.page==='chat'?chat():null),people=[...chars(),...storyNpcs()],known=existing?.knownBy||presentActors(context).map(x=>x.id);return`<div class="modal-layer"><section class="modal"><div class="modal-handle"></div><div class="modal-head"><h2>${existing?'编辑记忆':'添加记忆'}</h2><button class="icon-btn" data-close>×</button></div><form class="form" id="memory-form"><div class="field"><label>发生了什么</label><textarea name="text" required>${e(existing?.text||source?.text||'')}</textarea></div><div class="field"><label>时间</label><input name="when" value="${e(existing?.when||'刚刚')}" /></div><div class="field"><label>谁知道这件事</label><div class="check-list compact-checks">${people.map(x=>`<label class="check-row"><input type="checkbox" name="knownBy" value="${x.id}" ${known.includes(x.id)?'checked':''}/>${av(x,true)}<span>${e(x.name)}${x.isNpc?' · NPC':''}</span></label>`).join('')}</div></div><input type="hidden" name="sourceChatId" value="${e(existing?.sourceChatId||source?.chatId||context?.id||'')}"/><div class="modal-actions"><button type="button" class="btn" data-close>取消</button><button class="btn primary">保存</button></div>${existing?`<button type="button" class="btn danger full" data-delete-memory="${existing.id}">${I.trash}删除记忆</button>`:''}</form></section></div>`}

window.modal=function(){if(state.modal==='storySwitcher')return storySwitcherModal();if(state.modal==='storyMenu')return storyMenuModal();if(state.modal==='editScene')return sceneEditorModal();return V2.modal()}

window.memoryContent=function(){const ms=db.memories.filter(x=>x.storyId===db.currentStoryId);return`<div class="memory-list v3-memory-list">${ms.map(m=>`<article class="memory-card"><div class="memory-dot"></div><div><div class="memory-text">${e(m.text)}</div><div class="memory-meta">${e(m.when)}${m.sourceChatId?` · ${e(chat(m.sourceChatId)?.name||'原场景')}`:''}</div><div class="memory-access">知道：${e(m.knownBy.map(id=>actor(id)?.name).filter(Boolean).join('、')||'无人')}</div></div><button class="row-edit" data-edit-memory="${m.id}">${I.edit}</button></article>`).join('')||'<div class="quiet-empty">还没有共同记忆。</div>'}</div>`}

window.render=function(){const pages={home:homePage,story:storyPage,characters:charactersPage,chats:chatsPage,chat:chatPage,scenes:scenesPage,settings:settingsPage,memory:memoriesPage};document.querySelector('#app').innerHTML=(pages[state.page]||homePage)();bind();if(state.page==='chat'){const x=document.querySelector('#messages');if(x)x.scrollTop=x.scrollHeight}}
window.go=function(p){if(p==='story'&&!story())p='home';state.page=p;state.modal=null;if(p!=='settings')state.settingsView='';render()}

window.bind=function(){V2.bind();
 document.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>{const c=chat(x.dataset.chat);if(c){db.currentStoryId=c.storyId;story().lastChatId=c.id;save()}state.chatId=x.dataset.chat;go('chat')});
 document.querySelectorAll('[data-story-switch]').forEach(x=>x.onclick=()=>{state.modal='storySwitcher';render()});
 document.querySelectorAll('[data-switch-story]').forEach(x=>x.onclick=()=>{db.currentStoryId=x.dataset.switchStory;const first=chats()[0];if(first)state.chatId=first.id;save();state.modal=null;state.page='chats';render()});
 document.querySelectorAll('[data-story-menu]').forEach(x=>x.onclick=()=>{state.modal='storyMenu';render()});
 document.querySelectorAll('[data-setting-section]').forEach(x=>x.onclick=()=>{const key=x.dataset.settingSection;if(key==='ai'){state.settingsView='ai';render()}else toast(key==='about'?'StoryVerse · 让故事世界持续存在':'这一项将在后续逐步完善')});
 document.querySelectorAll('[data-edit-scene]').forEach(x=>x.onclick=()=>{state.modal='editScene';state.editingId=x.dataset.editScene;render()});
 const sceneForm=document.querySelector('#v3-scene-form');if(sceneForm)sceneForm.onsubmit=ev=>{ev.preventDefault();const d=formObj(sceneForm),allowed=[...sceneForm.querySelectorAll('[name=allowed]:checked')].map(x=>x.value),present=[...sceneForm.querySelectorAll('[name=present]:checked')].map(x=>x.value);present.forEach(id=>{if(!allowed.includes(id))allowed.push(id)});let c=state.editingId?chat(state.editingId):null;if(!c){c={id:uid('scene'),storyId:db.currentStoryId,type:'scene',name:d.name,memberIds:[],updatedAt:now(),scene:{}};db.chats.push(c)}c.name=d.name;c.updatedAt=now();c.scene={...c.scene,description:d.description,status:d.status||'场景持续存在',allowedCharacterIds:allowed,presentCharacterIds:present,npcIds:c.scene.npcIds||[],autoMemory:c.scene.autoMemory!==false};c.memberIds=[...present];const npcName=d.npcName.trim(),existing=npc(c.scene.npcIds[0]);if(npcName){if(existing)existing.name=npcName;else{const n={id:uid('npc'),storyId:c.storyId,sceneId:c.id,name:npcName,role:`${c.name}的固定 NPC`,intro:`长期在${c.name}活动，负责自然回应来到这里的人。`,personality:'友善、自然',speech:'简洁礼貌',tone:4,isNpc:true,agentId:''};db.npcs.push(n);c.scene.npcIds.push(n.id)}}else if(existing){db.npcs=db.npcs.filter(x=>x.id!==existing.id);c.scene.npcIds=[]}save();state.editingId=null;state.modal=null;state.chatId=c.id;go('chat');toast('场景已保存')};
 document.querySelectorAll('[data-enter-cafe]').forEach(x=>x.onclick=()=>enterCafe(x.dataset.enterCafe));
 document.querySelectorAll('[data-export-story]').forEach(x=>x.onclick=()=>exportStory());
 const toggle=document.querySelector('[data-scene-auto]');if(toggle)toggle.onclick=()=>{const c=chat();c.scene.autoMemory=!c.scene.autoMemory;save();render()};
}

function enterCafe(characterId){let cafe=sceneChats().find(c=>c.name.trim()==='咖啡厅');const person=char(characterId);if(!person)return;if(!cafe){cafe={id:uid('scene-cafe'),storyId:db.currentStoryId,type:'scene',name:'咖啡厅',memberIds:[person.id],updatedAt:now(),scene:{description:'学院附近温暖安静的咖啡厅，木质桌椅旁飘着咖啡香。',status:'午后，店里客人不多',allowedCharacterIds:[person.id],presentCharacterIds:[person.id],npcIds:[],autoMemory:true}};db.chats.push(cafe);const keeper={id:uid('npc'),storyId:db.currentStoryId,sceneId:cafe.id,name:'店长',role:'咖啡厅店长',intro:'熟悉来往客人，待人温和。',personality:'友善、细心',speech:'简洁礼貌',tone:4,isNpc:true,agentId:''};db.npcs.push(keeper);cafe.scene.npcIds=[keeper.id];db.messages.push({id:uid('m'),chatId:cafe.id,senderId:keeper.id,text:'欢迎光临，请问两位需要点什么？',time:timeNow()})}else{if(!cafe.scene.allowedCharacterIds.includes(person.id))cafe.scene.allowedCharacterIds.push(person.id);if(!cafe.scene.presentCharacterIds.includes(person.id))cafe.scene.presentCharacterIds.push(person.id);cafe.memberIds=[...cafe.scene.presentCharacterIds];if(!cafe.scene.npcIds.length){const keeper={id:uid('npc'),storyId:cafe.storyId,sceneId:cafe.id,name:'店长',role:'咖啡厅店长',intro:'熟悉来往客人，待人温和。',personality:'友善、细心',speech:'简洁礼貌',tone:4,isNpc:true,agentId:''};db.npcs.push(keeper);cafe.scene.npcIds=[keeper.id]}}cafe.updatedAt=now();story().lastChatId=cafe.id;save();state.chatId=cafe.id;go('chat');toast(`${person.name}和你进入了咖啡厅`)}
function exportStory(){const s=story(),chatIds=db.chats.filter(c=>c.storyId===s.id).map(c=>c.id),payload={version:3,exportedAt:now(),story:s,characters:chars(),chats:db.chats.filter(c=>c.storyId===s.id),npcs:storyNpcs(),messages:db.messages.filter(m=>chatIds.includes(m.chatId)),memories:db.memories.filter(m=>m.storyId===s.id)};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`StoryVerse-${s.name}.json`;a.click();URL.revokeObjectURL(url);toast('故事数据已导出')}

window.selectResponders=function(c,text){const members=presentActors(c);if(!members.length)return[];const mentioned=members.filter(x=>text.includes(x.name));if(mentioned.length)return mentioned.slice(0,2);let score=[...text].reduce((n,x)=>n+x.charCodeAt(0),0)+msgList(c.id).length,count=/[？?谁]|大家|你们/.test(text)?Math.min(2,members.length):1;if(score%7===0)count=Math.min(3,members.length);const start=score%members.length;return Array.from({length:count},(_,i)=>members[(start+i)%members.length])}
window.mockReply=function(c,text,index){if(c.isNpc){if(c.name.includes('店长'))return/咖啡|喝|点/.test(text)?'好的，请稍等。今天的手冲和热可可都很受欢迎。':'欢迎来到这里，需要帮助的话随时叫我。';return`${c.name}礼貌地点了点头。`}const low=text.toLowerCase(),p=c.personality||'';if(p.includes('傲娇'))return low.includes('谢谢')?'谁、谁要你谢了。我只是顺手而已。':`哼，${text.length>18?'这件事听起来可没那么简单。':'我知道了。'}不过你别一个人乱来。`;if(p.includes('热情'))return/咖啡/.test(text)?'好呀！学校附近刚好有一家咖啡厅，我们现在就去吧！':`真的？那我也要参加！${index?'而且刚才说得很有道理。':'我们现在就开始准备吧！'}`;if(p.includes('冷静'))return`先确认情况，再行动。${text.includes('森林')?'恢复药和照明术都要准备。':''}`;return'我明白你的意思，我们可以试试看。'}
window.systemPrompt=function(c,target){const s=story(),p=s.player,known=db.memories.filter(m=>m.storyId===s.id&&m.knownBy.includes(c.id)),memoryText=known.length?known.map(m=>`- ${m.text}（${m.when}）`).join('\n'):'- 暂无',scene=isScene(target);return`你正在扮演“${c.name}”${c.isNpc?`，你是属于“${target.name}”的固定 NPC`:`，参加故事《${s.name}》`}。\n世界观：${s.worldview}\n故事背景：${s.background}\n当前剧情：${s.plot}\n${scene?`当前场景：${target.name}\n场景介绍：${target.scene.description}\n场景状态：${target.scene.status}\n当前在场：我、${presentActors(target).map(x=>x.name).join('、')}`:'这是你与用户的一对一私聊。'}\n用户角色：姓名“${p.name||'未知'}”，性别“${p.gender||'未知'}”，年龄“${p.age||'未知'}”，身份“${p.identity||'未知'}”，外貌“${p.appearance||'未知'}”。\n你的身份：${c.role||''}\n性格：${c.personality||''}\n说话方式：${c.speech||''}\n背景：${c.background||c.intro||''}\n与用户关系：${c.relation||''}\n你明确知道的记忆：\n${memoryText}\n不在当前场景时发生的对话，除非出现在你的知情记忆中，否则你不知道。只控制${c.name}本人，绝不替用户说话或行动；只输出自然回复，不要写“${c.name}：”前缀。`}
window.requestAI=async function(c,target){const bot=agent(c.agentId),source=api(bot?.apiId);if(!bot||!source)throw new Error('这个人物还没有绑定可用的智能体。');const history=msgList(target.id).filter(m=>m.senderId!=='system'||m.type==='storyEvent').slice(-18).map(m=>m.type==='storyEvent'?{role:'user',content:`[场景事件] ${m.title||''}：${m.text}`}:{role:m.senderId==='user'?'user':'assistant',content:`${m.senderId==='user'?(story().player.name||'用户'):(actor(m.senderId)?.name||'角色')}：${source.separator?splitChinese(m.text):m.text}`}),res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:source.baseUrl,apiKey:source.apiKey,model:bot.model,messages:[{role:'system',content:systemPrompt(c,target)},...history],temperature:.86,maxTokens:700})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'连接 AI 失败，请检查智能体和接口设置。');return normalize(body.content||'',c,target)}
window.requestSummary=async function(target,turn){const person=presentActors(target).find(c=>agent(c?.agentId)&&api(agent(c.agentId)?.apiId));if(!person)throw new Error('当前聊天没有绑定可用智能体，暂时无法自动总结。');const bot=agent(person.agentId),source=api(bot.apiId),lines=turn.map(m=>`${m.senderId==='user'?(story().player.name||'我'):(actor(m.senderId)?.name||'角色')}：${m.text}`).join('\n'),res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:source.baseUrl,apiKey:source.apiKey,model:bot.model,messages:[{role:'system',content:'你是严谨的故事记忆整理器，只记录已经发生的事实。'},{role:'user',content:`地点：${isScene(target)?target.name:'私聊'}\n${lines}\n请用中文40字以内总结已发生且值得记住的事实，只输出正文。`}],temperature:.25,maxTokens:160})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'自动总结失败。');return String(body.content||'').replace(/丨/g,'').replace(/^\s*(?:当前记忆|记忆|总结)\s*[：:]\s*/,'').trim()}
window.summarizeScene=async function(target,turn,manual=false,replaceLatest=false){if(!manual&&!target.scene?.autoMemory)return false;state.summarizing=true;render();try{const summary=await requestSummary(target,turn);if(!summary)throw new Error('智能体没有返回记忆总结。');if(replaceLatest){const latest=db.memories.filter(m=>m.sourceChatId===target.id&&m.auto).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];if(latest)db.memories=db.memories.filter(m=>m.id!==latest.id)}db.memories.push({id:uid('mem'),storyId:target.storyId,text:summary,when:`今天 ${timeNow()}`,knownBy:presentActors(target).map(x=>x.id),sourceChatId:target.id,sceneId:isScene(target)?target.id:'',createdAt:now(),auto:true});target.scene.lastSummaryError='';save();if(manual)toast('已生成新的当前记忆');return true}catch(err){target.scene.lastSummaryError=err.message||'自动总结失败';save();if(manual)toast(target.scene.lastSummaryError);return false}finally{state.summarizing=false;render()}}
window.sendMessage=async function(raw){const text=String(raw||'').trim();if(!text||state.sending)return;const c=chat();if(!c)return;const turn=[],userMessage={id:uid('m'),chatId:c.id,senderId:'user',text,time:timeNow()};db.messages.push(userMessage);turn.push(userMessage);c.updatedAt=now();story().updatedAt=now();story().lastChatId=c.id;save();state.sending=true;render();const responders=c.type==='private'?presentActors(c):selectResponders(c,text);for(let i=0;i<responders.length;i++){const person=responders[i],useAI=!!agent(person.agentId);state.typingId=person.id;render();await new Promise(r=>setTimeout(r,useAI?350:550+i*180));try{const reply=useAI?await requestAI(person,c):mockReply(person,text,i),answer={id:uid('m'),chatId:c.id,senderId:person.id,text:reply,time:timeNow()};db.messages.push(answer);turn.push(answer);save()}catch(err){db.messages.push({id:uid('err'),chatId:c.id,senderId:person.id,text:err.message||'这条消息没有成功发送。',time:timeNow(),error:true,original:text});save();break}state.typingId=null;render()}state.sending=false;state.typingId=null;render();if(turn.length>1)await summarizeScene(c,turn)}
window.regenerateMessage=async function(target){const c=chat(target.chatId);if(!c)return;if(target.senderId!=='user'){const person=actor(target.senderId);if(!person)return;const index=db.messages.findIndex(x=>x.id===target.id);db.messages.splice(index,1);state.sending=true;state.typingId=person.id;render();try{target.text=agent(person.agentId)?await requestAI(person,c):mockReply(person,'请重新回复上一条消息。',0);target.time=timeNow();db.messages.splice(index,0,target);save();toast('回复已重新生成')}catch(err){db.messages.splice(index,0,target);save();toast(err.message||'重新生成失败')}state.sending=false;state.typingId=null;render();return}return V2.regenerateMessage(target)}
window.deleteCharacter=function(id){const c=char(id);if(!c||!confirm(`确定删除“${c.name}”吗？相关私聊记录也会删除。`))return;const privateIds=db.chats.filter(x=>x.type==='private'&&x.memberIds.includes(id)).map(x=>x.id);db.messages=db.messages.filter(m=>!privateIds.includes(m.chatId));db.chats=db.chats.filter(x=>!privateIds.includes(x.id));db.chats.filter(isScene).forEach(x=>{x.scene.allowedCharacterIds=x.scene.allowedCharacterIds.filter(y=>y!==id);x.scene.presentCharacterIds=x.scene.presentCharacterIds.filter(y=>y!==id);x.memberIds=x.memberIds.filter(y=>y!==id)});db.memories.forEach(m=>m.knownBy=m.knownBy.filter(x=>x!==id));db.characters=db.characters.filter(x=>x.id!==id);save();state.modal=null;render();toast('人物已删除')}
window.deleteStory=function(id){const s=db.stories.find(x=>x.id===id);if(!s||!confirm(`确定删除故事“${s.name}”及其中全部内容吗？`))return;const ids=db.chats.filter(x=>x.storyId===id).map(x=>x.id);db.messages=db.messages.filter(x=>!ids.includes(x.chatId));db.chats=db.chats.filter(x=>x.storyId!==id);db.characters=db.characters.filter(x=>x.storyId!==id);db.npcs=db.npcs.filter(x=>x.storyId!==id);db.memories=db.memories.filter(x=>x.storyId!==id);db.stories=db.stories.filter(x=>x.id!==id);db.currentStoryId=db.stories[0]?.id||'';save();go('home')}

state.settingsView='';
if(params.get('selftest')!=='1')render();
